const SONG_STORAGE='song-note-songs-v1';const GEMINI_KEY_STORAGE='neet-note-gemini-api-key';const params=new URLSearchParams(location.search);const songId=params.get('song');let currentSong=null;let chatHistory=[];let lastAnswer='';
const $=id=>document.getElementById(id);const chatMessages=$('chatMessages');const chatInput=$('chatInput');const sendChatBtn=$('sendChatBtn');
function loadSongs(){try{return JSON.parse(localStorage.getItem(SONG_STORAGE))||[]}catch{return[]}}
function saveSongs(songs){localStorage.setItem(SONG_STORAGE,JSON.stringify(songs))}
function loadSong(){const songs=loadSongs();currentSong=songs.find(s=>s.id===songId)||songs[0]||null;if(!currentSong){$('contextTitle').textContent='曲が見つかりません';return}$('contextTitle').textContent=currentSong.title||'無題の曲';$('contextStructure').value=currentSong.structure||'';$('contextChords').value=currentSong.chords||'';$('moodInput').value=currentSong.mood||'';$('themeInput').value=currentSong.theme||'';$('lyricIdeaInput').value=currentSong.lyricIdea||currentSong.lyrics||'';$('contextMeta').innerHTML='';[currentSong.artist,currentSong.key&&`Key ${currentSong.key}`,currentSong.bpm&&`${currentSong.bpm} BPM`,currentSong.timeSignature].filter(Boolean).forEach(t=>{const s=document.createElement('span');s.textContent=t;$('contextMeta').appendChild(s)});$('backToEditorLink').href=`index.html?song=${encodeURIComponent(currentSong.id)}`}
function persistAssistantInputs(){if(!currentSong)return;const songs=loadSongs();const i=songs.findIndex(s=>s.id===currentSong.id);if(i<0)return;songs[i]={...songs[i],structure:$('contextStructure').value,chords:$('contextChords').value,mood:$('moodInput').value,theme:$('themeInput').value,lyricIdea:$('lyricIdeaInput').value,updatedAt:new Date().toISOString()};currentSong=songs[i];saveSongs(songs)}
function getKey(){return localStorage.getItem(GEMINI_KEY_STORAGE)||''}function mask(k){return k?`${k.slice(0,6)}…${k.slice(-4)}`:''}function refreshKey(){const k=getKey();$('geminiApiKeyInput').value=k;$('apiKeyStatus').textContent=k?`${mask(k)} を使用中`:'未設定'}
function addMessage(text,role){const d=document.createElement('div');d.className=`chat-message ${role==='user'?'user-message':'assistant-message'}`;d.textContent=text;chatMessages.appendChild(d);chatMessages.scrollTop=chatMessages.scrollHeight}
function songContext(){return `曲名: ${currentSong?.title||'無題'}\nキー: ${currentSong?.key||'未設定'}\nBPM: ${currentSong?.bpm||'未設定'}\n拍子: ${currentSong?.timeSignature||'未設定'}\n構成: ${$('contextStructure').value||'未設定'}\n雰囲気: ${$('moodInput').value||'未設定'}\nテーマ: ${$('themeInput').value||'未設定'}\nコード進行:\n${$('contextChords').value||'未入力'}\n歌詞断片:\n${$('lyricIdeaInput').value||'未入力'}`}
async function sendMessage(){const q=chatInput.value.trim();if(!q)return;const key=getKey();if(!key){addMessage('先にGemini APIキーを設定してね。','assistant');return}persistAssistantInputs();addMessage(q,'user');chatInput.value='';chatHistory.push({role:'user',parts:[{text:q}]});sendChatBtn.disabled=true;sendChatBtn.textContent='考え中…';try{const prompt=`あなたは実践的な作曲アドバイザーです。既存アーティストの直接的な模倣は避け、一般的な音楽的特徴として日本語で具体的に答えてください。\n\n${songContext()}\n\n相談: ${q}`;const contents=[...chatHistory.slice(-8,-1),{role:'user',parts:[{text:prompt}]}];const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents,generationConfig:{temperature:.8,maxOutputTokens:1800}})});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`HTTP ${r.status}`);const text=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!text)throw new Error('回答を読み取れませんでした');lastAnswer=text;chatHistory.push({role:'model',parts:[{text}]});addMessage(text,'assistant')}catch(e){addMessage(`Geminiへの接続に失敗しました：${e.message}`,'assistant')}finally{sendChatBtn.disabled=false;sendChatBtn.textContent='送信'}}
$('saveApiKeyBtn').addEventListener('click',()=>{const k=$('geminiApiKeyInput').value.trim();if(!k)return alert('APIキーを入力してね');localStorage.setItem(GEMINI_KEY_STORAGE,k);refreshKey()});$('clearApiKeyBtn').addEventListener('click',()=>{localStorage.removeItem(GEMINI_KEY_STORAGE);refreshKey()});$('reloadSongBtn').addEventListener('click',loadSong);$('clearChatBtn').addEventListener('click',()=>{chatHistory=[];lastAnswer='';chatMessages.innerHTML='';addMessage('履歴を消したよ。新しく相談してね。','assistant')});sendChatBtn.addEventListener('click',sendMessage);chatInput.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')sendMessage()});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{chatInput.value=b.dataset.prompt;sendMessage()}));$('copyLastBtn').addEventListener('click',async()=>{if(!lastAnswer)return alert('まだ回答がないよ');await navigator.clipboard.writeText(lastAnswer);alert('コピーしたよ')});$('applyChordBtn').addEventListener('click',()=>{if(!lastAnswer)return alert('まだ回答がないよ');const current=$('contextChords').value;$('contextChords').value=current+(current?'\n\n':'')+'[AIメモ]\n'+lastAnswer;persistAssistantInputs();alert('コード進行メモへ追加したよ')});['contextStructure','contextChords','moodInput','themeInput','lyricIdeaInput'].forEach(id=>$(id).addEventListener('change',persistAssistantInputs));loadSong();refreshKey();