const STORAGE_KEY = "song-note-songs-v1";

const listView = document.getElementById("listView");
const editorView = document.getElementById("editorView");
const songList = document.getElementById("songList");
const emptyState = document.getElementById("emptyState");
const searchInput = document.getElementById("searchInput");
const saveStatus = document.getElementById("saveStatus");

const fields = {
  id: document.getElementById("songId"), title: document.getElementById("titleInput"), lyricist: document.getElementById("lyricistInput"),
  composer: document.getElementById("composerInput"), arranger: document.getElementById("arrangerInput"), artist: document.getElementById("artistInput"),
  productionDate: document.getElementById("productionDateInput"), key: document.getElementById("keyInput"), bpm: document.getElementById("bpmInput"),
  timeSignature: document.getElementById("timeSignatureInput"), structure: document.getElementById("structureInput"), chords: document.getElementById("chordsInput"),
  mood: document.getElementById("moodInput"), theme: document.getElementById("themeInput"), lyricIdea: document.getElementById("lyricIdeaInput")
};
const audioInput=document.getElementById("audioInput"),audioPreviewWrap=document.getElementById("audioPreviewWrap"),audioPreview=document.getElementById("audioPreview"),songCardTemplate=document.getElementById("songCardTemplate");
let songs=loadSongs(),currentAudioData="",saveTimer=null;
function loadSongs(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(p)?p:[]}catch{return[]}}
function persistSongs(){localStorage.setItem(STORAGE_KEY,JSON.stringify(songs))}function makeId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())}
function newSong(){const song={id:makeId(),title:"",lyricist:"",composer:"",arranger:"",artist:"",productionDate:"",key:"",bpm:"",timeSignature:"",structure:"",chords:"",mood:"",theme:"",lyricIdea:"",audioData:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};songs.unshift(song);persistSongs();openEditor(song.id)}
function openEditor(id){const song=songs.find(item=>item.id===id);if(!song)return;fields.id.value=song.id;fields.title.value=song.title||"";fields.lyricist.value=song.lyricist||"";fields.composer.value=song.composer||"";fields.arranger.value=song.arranger||"";fields.artist.value=song.artist||"";fields.productionDate.value=song.productionDate||"";fields.key.value=song.key||"";fields.bpm.value=song.bpm||"";fields.timeSignature.value=song.timeSignature||"";fields.structure.value=song.structure||"";fields.chords.value=song.chords||"";fields.mood.value=song.mood||"";fields.theme.value=song.theme||"";fields.lyricIdea.value=song.lyricIdea||song.lyrics||"";currentAudioData=song.audioData||"";renderAudioPreview();saveStatus.textContent="保存済み";listView.classList.remove("active");editorView.classList.add("active");window.scrollTo({top:0,behavior:"instant"})}
function showList(){autoSaveNow();editorView.classList.remove("active");listView.classList.add("active");renderSongList();history.replaceState(null,"",`${location.pathname}?mode=note`);window.scrollTo({top:0,behavior:"instant"})}
function collectFormData(){return{title:fields.title.value.trim(),lyricist:fields.lyricist.value.trim(),composer:fields.composer.value.trim(),arranger:fields.arranger.value.trim(),artist:fields.artist.value.trim(),productionDate:fields.productionDate.value,key:fields.key.value,bpm:fields.bpm.value,timeSignature:fields.timeSignature.value,structure:fields.structure.value,chords:fields.chords.value,mood:fields.mood.value,theme:fields.theme.value.trim(),lyricIdea:fields.lyricIdea.value,audioData:currentAudioData}}
function scheduleSave(){saveStatus.textContent="保存中…";clearTimeout(saveTimer);saveTimer=setTimeout(autoSaveNow,350)}
function autoSaveNow(){clearTimeout(saveTimer);const id=fields.id.value;if(!id)return;const i=songs.findIndex(item=>item.id===id);if(i===-1)return;songs[i]={...songs[i],...collectFormData(),updatedAt:new Date().toISOString()};persistSongs();saveStatus.textContent="保存済み"}
function deleteSongFromList(id){const song=songs.find(item=>item.id===id);if(!song)return;const title=song.title||"無題の曲";if(!confirm(`「${title}」を削除しますか？\nこの操作は元に戻せません。`))return;songs=songs.filter(item=>item.id!==id);persistSongs();renderSongList()}
function renderSongList(){const q=searchInput.value.trim().toLowerCase();const filtered=songs.slice().sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(song=>[song.title,song.lyricist,song.composer,song.arranger,song.artist,song.productionDate,song.key,song.bpm,song.timeSignature,song.structure,song.chords,song.mood,song.theme,song.lyricIdea,song.lyrics].join(" ").toLowerCase().includes(q));songList.innerHTML="";emptyState.classList.toggle("hidden",songs.length!==0||q!=="");if(songs.length>0&&filtered.length===0){songList.innerHTML='<div class="empty-state"><h2>見つかりませんでした</h2><p>別の言葉で検索してみてね。</p></div>';return}filtered.forEach(song=>{const node=songCardTemplate.content.cloneNode(true),card=node.querySelector(".song-card"),title=node.querySelector(".song-title"),meta=node.querySelector(".song-meta"),date=node.querySelector(".song-date"),preview=node.querySelector(".song-preview"),deleteButton=node.querySelector(".song-delete-button");title.textContent=song.title||"無題の曲";const items=[song.artist||"",song.mood||"",song.key?`Key ${song.key}`:"",song.bpm?`${song.bpm} BPM`:""].filter(Boolean);meta.textContent=items.length?items.join(" · "):"作品情報未設定";date.textContent=new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric"}).format(new Date(song.updatedAt));preview.textContent=song.lyricIdea?.trim()||song.theme?.trim()||song.chords?.trim()||song.structure?.trim()||"まだ内容がありません";deleteButton?.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();deleteSongFromList(song.id)});card.addEventListener("click",()=>openEditor(song.id));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openEditor(song.id)}});songList.appendChild(node)})}
function deleteCurrentSong(){const id=fields.id.value;if(!id)return;const song=songs.find(item=>item.id===id),title=song?.title||"無題の曲";if(!confirm(`「${title}」を削除しますか？`))return;songs=songs.filter(item=>item.id!==id);persistSongs();fields.id.value="";showList()}
function renderAudioPreview(){if(currentAudioData){audioPreview.src=currentAudioData;audioPreviewWrap.classList.remove("hidden")}else{audioPreview.removeAttribute("src");audioPreview.load();audioPreviewWrap.classList.add("hidden")}}
function handleAudioFile(file){if(!file)return;const max=4*1024*1024;if(file.size>max){alert("音源が大きすぎます。4MB以下のファイルを選んでください。");audioInput.value="";return}const reader=new FileReader();reader.onload=()=>{currentAudioData=reader.result;renderAudioPreview();scheduleSave()};reader.readAsDataURL(file)}
function copyCreatorNameToAll(){const name=fields.lyricist.value.trim()||fields.composer.value.trim()||fields.arranger.value.trim();if(!name){alert("作詞・作曲・編曲のどれか1つに名前を入力してね。");fields.lyricist.focus();return}fields.lyricist.value=name;fields.composer.value=name;fields.arranger.value=name;[fields.lyricist,fields.composer,fields.arranger].forEach(field=>field.dispatchEvent(new Event("input",{bubbles:true})));scheduleSave()}

const menuOpenBtn=document.getElementById("menuOpenBtn"),menuCloseBtn=document.getElementById("menuCloseBtn"),sideMenu=document.getElementById("sideMenu"),menuOverlay=document.getElementById("menuOverlay");
function addExtraMenuLink(){if(!sideMenu||sideMenu.querySelector('[href="https://akito0802.github.io/-h/"]'))return;const link=document.createElement("a");link.className="menu-link";link.href="https://akito0802.github.io/-h/";link.innerHTML='<span class="menu-icon">🎵</span><span>-h</span>';sideMenu.appendChild(link)}
function normalizeCodeTableLink(){if(!sideMenu)return;const links=[...sideMenu.querySelectorAll("a.menu-link")];const target=links.find(link=>link.href.includes("Cordhyo-"));if(!target)return;target.href="https://akito0802.github.io/Cordhyo-/index.html";const label=target.querySelector("span:last-child");if(label)label.textContent="コード表"}
function openMenu(){sideMenu?.classList.add("open");menuOverlay?.classList.add("open");sideMenu?.setAttribute("aria-hidden","false");menuOpenBtn?.setAttribute("aria-expanded","true");document.body.style.overflow="hidden"}
function closeMenu(){sideMenu?.classList.remove("open");menuOverlay?.classList.remove("open");sideMenu?.setAttribute("aria-hidden","true");menuOpenBtn?.setAttribute("aria-expanded","false");document.body.style.overflow=""}
function cameFromAnotherMode(){return /akito0802\.github\.io\/(scale|-h|Cordhyo-)\//.test(document.referrer)}
function showModeLauncher(){const params=new URLSearchParams(location.search);if(params.has("song")||params.get("mode")==="note"||cameFromAnotherMode()){if(!params.has("song")&&params.get("mode")!=="note")history.replaceState(null,"",`${location.pathname}?mode=note`);return}const style=document.createElement("link");style.rel="stylesheet";style.href="splash.css?v=6";document.head.appendChild(style);const script=document.createElement("script");script.src="splash.js?v=6";document.body.appendChild(script)}

addExtraMenuLink();normalizeCodeTableLink();menuOpenBtn?.addEventListener("click",openMenu);menuCloseBtn?.addEventListener("click",closeMenu);menuOverlay?.addEventListener("click",closeMenu);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeMenu()});
document.getElementById("newSongBtn").addEventListener("click",newSong);document.getElementById("emptyNewSongBtn").addEventListener("click",newSong);document.getElementById("backBtn").addEventListener("click",showList);document.getElementById("doneBtn").addEventListener("click",showList);document.getElementById("deleteBtn").addEventListener("click",deleteCurrentSong);Object.values(fields).forEach(field=>{if(field&&field.id!=="songId"){field.addEventListener("input",scheduleSave);field.addEventListener("change",scheduleSave)}});audioInput.addEventListener("change",e=>handleAudioFile(e.target.files[0]));document.getElementById("removeAudioBtn").addEventListener("click",()=>{currentAudioData="";audioInput.value="";renderAudioPreview();scheduleSave()});document.getElementById("copyCreatorNameBtn")?.addEventListener("click",copyCreatorNameToAll);searchInput.addEventListener("input",renderSongList);window.addEventListener("beforeunload",autoSaveNow);
document.getElementById("openAiPageBtn").addEventListener("click",()=>{autoSaveNow();const id=fields.id.value;if(id)location.href=`ai.html?song=${encodeURIComponent(id)}`});
renderSongList();const params=new URLSearchParams(location.search);const requestedSong=params.get("song");if(requestedSong)openEditor(requestedSong);else showModeLauncher();