const STORAGE_KEY = "song-note-songs-v1";

const listView = document.getElementById("listView");
const editorView = document.getElementById("editorView");
const songList = document.getElementById("songList");
const emptyState = document.getElementById("emptyState");
const searchInput = document.getElementById("searchInput");
const saveStatus = document.getElementById("saveStatus");

const fields = {
  id: document.getElementById("songId"), title: document.getElementById("titleInput"), lyricist: document.getElementById("lyricistInput"),
  composer: document.getElementById("composerInput"), arranger: document.getElementById("arrangerInput"), artist: document.getElementById("artistInput"),
  productionDate: document.getElementById("productionDateInput"), key: document.getElementById("keyInput"), bpm: document.getElementById("bpmInput"),
  timeSignature: document.getElementById("timeSignatureInput"), structure: document.getElementById("structureInput"), chords: document.getElementById("chordsInput"),
  mood: document.getElementById("moodInput"), theme: document.getElementById("themeInput"), lyricIdea: document.getElementById("lyricIdeaInput")
};
const audioInput=document.getElementById("audioInput"),audioPreviewWrap=document.getElementById("audioPreviewWrap"),audioPreview=document.getElementById("audioPreview"),songCardTemplate=document.getElementById("songCardTemplate");
let songs=loadSongs(),currentAudioData="",saveTimer=null;
function loadSongs(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(p)?p:[]}catch{return[]}}
function persistSongs(){localStorage.setItem(STORAGE_KEY,JSON.stringify(songs));createAutomaticBackup()}function makeId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())}
function newSong(){const song={id:makeId(),title:"",lyricist:"",composer:"",arranger:"",artist:"",productionDate:"",key:"",bpm:"",timeSignature:"",structure:"",chords:"",mood:"",theme:"",lyricIdea:"",audioData:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};songs.unshift(song);persistSongs();openEditor(song.id)}
function openEditor(id){const song=songs.find(item=>item.id===id);if(!song)return;fields.id.value=song.id;fields.title.value=song.title||"";fields.lyricist.value=song.lyricist||"";fields.composer.value=song.composer||"";fields.arranger.value=song.arranger||"";fields.artist.value=song.artist||"";fields.productionDate.value=song.productionDate||"";fields.key.value=song.key||"";fields.bpm.value=song.bpm||"";fields.timeSignature.value=song.timeSignature||"";fields.structure.value=song.structure||"";fields.chords.value=song.chords||"";fields.mood.value=song.mood||"";fields.theme.value=song.theme||"";fields.lyricIdea.value=song.lyricIdea||song.lyrics||"";currentAudioData=song.audioData||"";renderAudioPreview();saveStatus.textContent="保存済み";listView.classList.remove("active");editorView.classList.add("active");renderSections();renderChordButtons();window.scrollTo({top:0,behavior:"instant"})}
function showList(){autoSaveNow();editorView.classList.remove("active");listView.classList.add("active");renderSongList();history.replaceState(null,"",`${location.pathname}?mode=note`);window.scrollTo({top:0,behavior:"instant"})}
function collectFormData(){return{title:fields.title.value.trim(),lyricist:fields.lyricist.value.trim(),composer:fields.composer.value.trim(),arranger:fields.arranger.value.trim(),artist:fields.artist.value.trim(),productionDate:fields.productionDate.value,key:fields.key.value,bpm:fields.bpm.value,timeSignature:fields.timeSignature.value,structure:fields.structure.value,chords:fields.chords.value,mood:fields.mood.value,theme:fields.theme.value.trim(),lyricIdea:fields.lyricIdea.value,audioData:currentAudioData}}
function scheduleSave(){saveStatus.textContent="保存中…";clearTimeout(saveTimer);saveTimer=setTimeout(autoSaveNow,350)}
function autoSaveNow(){clearTimeout(saveTimer);const id=fields.id.value;if(!id)return;const i=songs.findIndex(item=>item.id===id);if(i===-1)return;songs[i]={...songs[i],...collectFormData(),updatedAt:new Date().toISOString()};persistSongs();saveStatus.textContent="保存済み"}
function deleteSongFromList(id){const song=songs.find(item=>item.id===id);if(!song)return;const title=song.title||"無題の曲";if(!confirm(`「${title}」を削除しますか？\nこの操作は元に戻せません。`))return;songs=songs.filter(item=>item.id!==id);persistSongs();renderSongList()}
function renderSongList(){const q=searchInput.value.trim().toLowerCase();const filtered=songs.slice().sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(song=>[song.title,song.lyricist,song.composer,song.arranger,song.artist,song.productionDate,song.key,song.bpm,song.timeSignature,song.structure,song.chords,song.mood,song.theme,song.lyricIdea,song.lyrics].join(" ").toLowerCase().includes(q));songList.innerHTML="";emptyState.classList.toggle("hidden",songs.length!==0||q!=="");if(songs.length>0&&filtered.length===0){songList.innerHTML='<div class="empty-state"><h2>見つかりませんでした</h2><p>別の言葉で検索してみてね。</p></div>';return}filtered.forEach(song=>{const node=songCardTemplate.content.cloneNode(true),card=node.querySelector(".song-card"),title=node.querySelector(".song-title"),meta=node.querySelector(".song-meta"),date=node.querySelector(".song-date"),preview=node.querySelector(".song-preview"),deleteButton=node.querySelector(".song-delete-button");title.textContent=song.title||"無題の曲";const items=[song.artist||"",song.mood||"",song.key?`Key ${song.key}`:"",song.bpm?`${song.bpm} BPM`:""].filter(Boolean);meta.textContent=items.length?items.join(" · "):"作品情報未設定";date.textContent=new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric"}).format(new Date(song.updatedAt));preview.textContent=song.lyricIdea?.trim()||song.theme?.trim()||song.chords?.trim()||song.structure?.trim()||"まだ内容がありません";deleteButton?.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();deleteSongFromList(song.id)});card.addEventListener("click",()=>openEditor(song.id));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openEditor(song.id)}});songList.appendChild(node)})}
function deleteCurrentSong(){const id=fields.id.value;if(!id)return;const song=songs.find(item=>item.id===id),title=song?.title||"無題の曲";if(!confirm(`「${title}」を削除しますか？`))return;songs=songs.filter(item=>item.id!==id);persistSongs();fields.id.value="";showList()}
function renderAudioPreview(){if(currentAudioData){audioPreview.src=currentAudioData;audioPreviewWrap.classList.remove("hidden")}else{audioPreview.removeAttribute("src");audioPreview.load();audioPreviewWrap.classList.add("hidden")}}
function handleAudioFile(file){if(!file)return;const max=4*1024*1024;if(file.size>max){alert("音源が大きすぎます。4MB以下のファイルを選んでください。");audioInput.value="";return}const reader=new FileReader();reader.onload=()=>{currentAudioData=reader.result;renderAudioPreview();scheduleSave()};reader.readAsDataURL(file)}
function copyCreatorNameToAll(){const name=fields.lyricist.value.trim()||fields.composer.value.trim()||fields.arranger.value.trim();if(!name){alert("作詞・作曲・編曲のどれか1つに名前を入力してね。");fields.lyricist.focus();return}fields.lyricist.value=name;fields.composer.value=name;fields.arranger.value=name;[fields.lyricist,fields.composer,fields.arranger].forEach(field=>field.dispatchEvent(new Event("input",{bubbles:true})));scheduleSave()}

const menuOpenBtn=document.getElementById("menuOpenBtn"),menuCloseBtn=document.getElementById("menuCloseBtn"),sideMenu=document.getElementById("sideMenu"),menuOverlay=document.getElementById("menuOverlay");
function addExtraMenuLink(){if(!sideMenu||sideMenu.querySelector('[href="https://akito0802.github.io/-h/"]'))return;const link=document.createElement("a");link.className="menu-link";link.href="https://akito0802.github.io/-h/";link.innerHTML='<span class="menu-icon">🎵</span><span>-h</span>';sideMenu.appendChild(link)}
function normalizeCodeTableLink(){if(!sideMenu)return;const links=[...sideMenu.querySelectorAll("a.menu-link")];const target=links.find(link=>link.href.includes("Cordhyo-"));if(!target)return;target.href="https://akito0802.github.io/Cordhyo-/index.html";const label=target.querySelector("span:last-child");if(label)label.textContent="コード表"}
function openMenu(){sideMenu?.classList.add("open");menuOverlay?.classList.add("open");sideMenu?.setAttribute("aria-hidden","false");menuOpenBtn?.setAttribute("aria-expanded","true");document.body.style.overflow="hidden"}
function closeMenu(){sideMenu?.classList.remove("open");menuOverlay?.classList.remove("open");sideMenu?.setAttribute("aria-hidden","true");menuOpenBtn?.setAttribute("aria-expanded","false");document.body.style.overflow=""}
function cameFromAnotherMode(){return /akito0802\.github\.io\/(scale|-h|Cordhyo-)\//.test(document.referrer)}
function showModeLauncher(){const params=new URLSearchParams(location.search);if(params.has("song")||params.get("mode")==="note"||cameFromAnotherMode()){if(!params.has("song")&&params.get("mode")!=="note")history.replaceState(null,"",`${location.pathname}?mode=note`);return}const style=document.createElement("link");style.rel="stylesheet";style.href="splash.css?v=6";document.head.appendChild(style);const script=document.createElement("script");script.src="splash.js?v=6";document.body.appendChild(script)}

/* 自動バックアップ */
const BACKUP_KEY="song-note-auto-backups-v1";
function createAutomaticBackup(){try{const now=Date.now(),backups=JSON.parse(localStorage.getItem(BACKUP_KEY)||"[]");const latest=backups[0];if(!latest||now-latest.createdAt>10*60*1000){backups.unshift({createdAt:now,songs:JSON.parse(JSON.stringify(songs))});localStorage.setItem(BACKUP_KEY,JSON.stringify(backups.slice(0,10)))}}catch(e){console.warn("backup failed",e)}}
function exportBackup(){autoSaveNow();const payload={app:"NEET NOTE",version:1,exportedAt:new Date().toISOString(),songs};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`neet-note-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function importBackup(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),incoming=Array.isArray(data)?data:data.songs;if(!Array.isArray(incoming))throw new Error();if(!confirm(`${incoming.length}曲を読み込みます。現在のデータは自動バックアップしてから置き換えます。`))return;createAutomaticBackup();songs=incoming;persistSongs();renderSongList();alert("バックアップを読み込んだよ！")}catch{alert("このファイルは読み込めなかったよ。NEET NOTEのバックアップJSONを選んでね。")}};reader.readAsText(file)}
function addBackupUi(){const toolbar=document.querySelector(".toolbar");if(!toolbar||document.getElementById("backupTools"))return;const wrap=document.createElement("div");wrap.id="backupTools";wrap.className="backup-tools";wrap.innerHTML='<button type="button" id="exportBackupBtn">⬇ バックアップ</button><label>⬆ 復元<input id="importBackupInput" type="file" accept="application/json,.json" hidden></label><small>10分ごと・最大10件を端末内に自動保存</small>';toolbar.appendChild(wrap);document.getElementById("exportBackupBtn").addEventListener("click",exportBackup);document.getElementById("importBackupInput").addEventListener("change",e=>importBackup(e.target.files[0]))}

/* コード試聴 */
let audioContext=null;
const NOTE_INDEX={C:0,"C#":1,Db:1,D:2,"D#":3,Eb:3,E:4,F:5,"F#":6,Gb:6,G:7,"G#":8,Ab:8,A:9,"A#":10,Bb:10,B:11};
function chordIntervals(name){const lower=name.toLowerCase();if(lower.includes("dim7"))return[0,3,6,9];if(lower.includes("m7b5")||lower.includes("m7♭5"))return[0,3,6,10];if(lower.includes("dim"))return[0,3,6];if(lower.includes("aug"))return[0,4,8];if(lower.includes("sus2"))return[0,2,7];if(lower.includes("sus4"))return[0,5,7];if(lower.includes("maj7"))return[0,4,7,11];if(/^([A-G][#b]?)m7/i.test(name))return[0,3,7,10];if(lower.includes("7"))return[0,4,7,10];if(/^([A-G][#b]?)m/i.test(name))return[0,3,7];return[0,4,7]}
function playChord(chord){const match=chord.match(/^([A-G](?:#|b)?)/);if(!match)return;audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const root=NOTE_INDEX[match[1]],now=audioContext.currentTime;chordIntervals(chord).forEach((interval,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),freq=440*Math.pow(2,((48+root+interval)-69)/12);osc.type="triangle";osc.frequency.value=freq;gain.gain.setValueAtTime(0.0001,now);gain.gain.exponentialRampToValueAtTime(.14/(i+1),now+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+1.25);osc.connect(gain).connect(audioContext.destination);osc.start(now+i*.012);osc.stop(now+1.3)})}
function extractChords(){const matches=fields.chords.value.match(/(?:^|\s|\|)([A-G](?:#|b)?(?:mMaj7|maj13|maj9|maj7|m13|m11|m9|m7b5|m7|m6|madd9|dim7|dim|aug|sus2|sus4|7sus4|add11|add9|13|11|9|7|6|5)?(?:\/[A-G](?:#|b)?)?)(?=\s|\||$)/g)||[];return matches.map(v=>v.trim()).filter(Boolean).slice(0,40)}
function renderChordButtons(){const box=document.getElementById("chordSoundBox");if(!box)return;const chords=extractChords();box.innerHTML=chords.length?chords.map(ch=>`<button type="button" data-chord="${ch}">▶ ${ch}</button>`).join(""):'<small>コード進行を書くと、ここに試聴ボタンが出るよ。</small>';box.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>playChord(btn.dataset.chord)))}
function addChordSoundUi(){const textarea=fields.chords;if(!textarea||document.getElementById("chordSoundBox"))return;const box=document.createElement("div");box.id="chordSoundBox";box.className="chord-sound-box";textarea.insertAdjacentElement("afterend",box);textarea.addEventListener("input",renderChordButtons);renderChordButtons()}

/* セクション管理 */
const DEFAULT_SECTIONS=["イントロ","Aメロ","Bメロ","サビ","間奏","Cメロ","ラスサビ","アウトロ"];
function parseSections(){return fields.structure.value.split("\n").map(line=>line.trim()).filter(Boolean).map(line=>{const parts=line.split(/\s*[｜|:]\s*/,2);return{name:parts[0],memo:parts[1]||""}})}
function saveSectionsFromUi(){const rows=[...document.querySelectorAll(".section-row")];fields.structure.value=rows.map(row=>{const name=row.querySelector(".section-name").value.trim(),memo=row.querySelector(".section-memo").value.trim();return name+(memo?`｜${memo}`:"")}).filter(Boolean).join("\n");fields.structure.dispatchEvent(new Event("input",{bubbles:true}))}
function renderSections(){const list=document.getElementById("sectionList");if(!list)return;const sections=parseSections();list.innerHTML="";(sections.length?sections:[]).forEach(addSectionRow)}
function addSectionRow(section={name:"",memo:""}){const list=document.getElementById("sectionList");if(!list)return;const row=document.createElement("div");row.className="section-row";row.draggable=true;row.innerHTML=`<span class="drag-handle">☰</span><input class="section-name" placeholder="セクション名" value="${String(section.name).replace(/"/g,"&quot;")}"><input class="section-memo" placeholder="コード・メモ" value="${String(section.memo).replace(/"/g,"&quot;")}"><button type="button" aria-label="削除">×</button>`;row.querySelectorAll("input").forEach(input=>input.addEventListener("input",saveSectionsFromUi));row.querySelector("button").addEventListener("click",()=>{row.remove();saveSectionsFromUi()});row.addEventListener("dragstart",()=>row.classList.add("dragging"));row.addEventListener("dragend",()=>{row.classList.remove("dragging");saveSectionsFromUi()});list.appendChild(row)}
function addSectionManager(){const structure=fields.structure;if(!structure||document.getElementById("sectionManager"))return;const manager=document.createElement("div");manager.id="sectionManager";manager.className="section-manager";manager.innerHTML='<div class="section-manager-head"><strong>曲のセクション</strong><select id="sectionPreset"><option value="">追加するセクション</option></select><button type="button" id="addSectionBtn">＋ 追加</button></div><div id="sectionList"></div><small>☰を長押しして並べ替え。内容は下の「曲の構成」と同期されるよ。</small>';structure.parentElement.insertBefore(manager,structure);const preset=manager.querySelector("#sectionPreset");DEFAULT_SECTIONS.forEach(name=>preset.add(new Option(name,name)));manager.querySelector("#addSectionBtn").addEventListener("click",()=>{addSectionRow({name:preset.value||"新しいセクション",memo:""});preset.value="";saveSectionsFromUi()});const list=manager.querySelector("#sectionList");list.addEventListener("dragover",e=>{e.preventDefault();const dragging=list.querySelector(".dragging");if(!dragging)return;const after=[...list.querySelectorAll(".section-row:not(.dragging)")].find(el=>e.clientY<=el.getBoundingClientRect().top+el.offsetHeight/2);list.insertBefore(dragging,after||null)});structure.addEventListener("change",renderSections);renderSections()}

function addEnhancementStyles(){const style=document.createElement("style");style.textContent=`.backup-tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.backup-tools button,.backup-tools label,.chord-sound-box button,.section-manager button{border:1px solid #d8d0c3;background:#fffdf8;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer}.backup-tools small{width:100%;color:#777}.chord-sound-box{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.chord-sound-box button{padding:7px 10px;background:#f7f0e5}.section-manager{margin:8px 0 12px;padding:14px;border:1px solid #e0d8ca;border-radius:14px;background:#faf7f1}.section-manager-head{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:10px}.section-manager-head strong{margin-right:auto}.section-manager select{min-height:38px;border:1px solid #d8d0c3;border-radius:9px;background:white;padding:0 8px}.section-row{display:grid;grid-template-columns:28px minmax(90px,.7fr) minmax(130px,1.5fr) 36px;gap:7px;align-items:center;margin:7px 0}.section-row input{width:100%;min-width:0;border:1px solid #d8d0c3;border-radius:9px;padding:9px}.drag-handle{cursor:grab;text-align:center}.section-row.dragging{opacity:.45}@media(max-width:600px){.section-row{grid-template-columns:26px 1fr 34px}.section-memo{grid-column:2/4}.backup-tools{align-items:stretch}.backup-tools button,.backup-tools label{flex:1;text-align:center}}`;document.head.appendChild(style)}

addExtraMenuLink();normalizeCodeTableLink();menuOpenBtn?.addEventListener("click",openMenu);menuCloseBtn?.addEventListener("click",closeMenu);menuOverlay?.addEventListener("click",closeMenu);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeMenu()});
document.getElementById("newSongBtn").addEventListener("click",newSong);document.getElementById("emptyNewSongBtn").addEventListener("click",newSong);document.getElementById("backBtn").addEventListener("click",showList);document.getElementById("doneBtn").addEventListener("click",showList);document.getElementById("deleteBtn").addEventListener("click",deleteCurrentSong);Object.values(fields).forEach(field=>{if(field&&field.id!=="songId"){field.addEventListener("input",scheduleSave);field.addEventListener("change",scheduleSave)}});audioInput.addEventListener("change",e=>handleAudioFile(e.target.files[0]));document.getElementById("removeAudioBtn").addEventListener("click",()=>{currentAudioData="";audioInput.value="";renderAudioPreview();scheduleSave()});document.getElementById("copyCreatorNameBtn")?.addEventListener("click",copyCreatorNameToAll);searchInput.addEventListener("input",renderSongList);window.addEventListener("beforeunload",autoSaveNow);
document.getElementById("openAiPageBtn").addEventListener("click",()=>{autoSaveNow();const id=fields.id.value;if(id)location.href=`ai.html?song=${encodeURIComponent(id)}`});
addEnhancementStyles();addBackupUi();addChordSoundUi();addSectionManager();createAutomaticBackup();
renderSongList();const params=new URLSearchParams(location.search);const requestedSong=params.get("song");if(requestedSong)openEditor(requestedSong);else showModeLauncher();