(()=>{
'use strict';
const cfg=window.NEET_FIREBASE_CONFIG||{};
const side=document.getElementById('sideMenu');
if(!side||document.getElementById('cloudSyncMenuButton'))return;
const TRACKED_KEYS=['song-note-songs-v1','neet-note-lyrics-memos-v1','neet-note-calendar-v1','neet-note-ideas-v1','neet-note-theme'];
const menuButton=document.createElement('button');menuButton.id='cloudSyncMenuButton';menuButton.className='menu-link';menuButton.type='button';menuButton.innerHTML='<span class="menu-icon">☁️</span><span id="cloudMenuLabel">ログイン・同期</span>';side.insertBefore(menuButton,side.querySelector('[data-theme-toggle]')||null);
const style=document.createElement('style');style.textContent='.cloud-modal{position:fixed;inset:0;z-index:32000;display:none;place-items:center;padding:18px;background:rgba(17,24,39,.58)}.cloud-modal.open{display:grid}.cloud-panel{width:min(430px,100%);padding:22px;border-radius:22px;background:var(--ui-surface,#fffdf8);color:var(--ui-text,#1f2937);box-shadow:0 24px 70px rgba(0,0,0,.3)}.cloud-head{display:flex;align-items:center;justify-content:space-between}.cloud-close{width:44px;height:44px;border:0;border-radius:50%;font-size:1.25rem}.cloud-actions{display:flex;gap:10px;flex-wrap:wrap}.cloud-account{display:none;margin:14px 0;padding:14px;border-radius:15px;background:rgba(52,199,89,.12)}.cloud-account.show{display:block}.cloud-toast{position:fixed;left:50%;top:18px;z-index:50000;width:min(92vw,430px);padding:15px 18px;border-radius:18px;background:#1c1c1e;color:#fff;transform:translate(-50%,-150%);opacity:0;transition:.3s}.cloud-toast.show{transform:translate(-50%,0);opacity:1}@media(max-width:600px){.cloud-modal{align-items:end;padding:0}.cloud-panel{border-radius:22px 22px 0 0;padding-bottom:calc(22px + env(safe-area-inset-bottom))}}';document.head.appendChild(style);
const modal=document.createElement('div');modal.className='cloud-modal';modal.innerHTML='<section class="cloud-panel"><div class="cloud-head"><h2>☁️ クラウド同期</h2><button class="cloud-close" type="button">×</button></div><div id="cloudAccount" class="cloud-account"><b>✅ Googleログイン済み</b><small id="cloudAccountText"></small></div><p id="cloudMessage">認証状態を確認中…</p><div class="cloud-actions"><button id="cloudLogin" class="primary-button" type="button" disabled>Googleでログイン</button><button id="cloudSync" class="ghost-button" type="button" hidden>今すぐ同期</button><button id="cloudLogout" class="ghost-button" type="button" hidden>ログアウト</button></div></section>';document.body.appendChild(modal);
const toast=document.createElement('div');toast.className='cloud-toast';document.body.appendChild(toast);let toastTimer;const notify=t=>{toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)};
const label=document.getElementById('cloudMenuLabel'),message=modal.querySelector('#cloudMessage'),account=modal.querySelector('#cloudAccount'),accountText=modal.querySelector('#cloudAccountText'),loginButton=modal.querySelector('#cloudLogin'),syncButton=modal.querySelector('#cloudSync'),logoutButton=modal.querySelector('#cloudLogout');
menuButton.onclick=()=>{modal.classList.add('open');document.body.style.overflow='hidden'};modal.querySelector('.cloud-close').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};
if(!(cfg.apiKey&&cfg.authDomain&&cfg.projectId&&cfg.appId)){message.textContent='Firebase設定が不足しているよ。';return;}
const readJson=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}};
const mergeArray=(a,b)=>{const m=new Map();[...(Array.isArray(b)?b:[]),...(Array.isArray(a)?a:[])].forEach(x=>{if(!x?.id)return;const old=m.get(x.id);if(!old||new Date(x.updatedAt||x.createdAt||0)>=new Date(old.updatedAt||old.createdAt||0))m.set(x.id,x)});return[...m.values()]};
const mergeCalendar=(a,b)=>{const out={...(b&&typeof b==='object'?b:{})};Object.entries(a&&typeof a==='object'?a:{}).forEach(([day,items])=>{out[day]=mergeArray(items,out[day])});return out};
const collect=()=>{const values={};TRACKED_KEYS.forEach(k=>{const raw=localStorage.getItem(k);if(raw!==null)values[k]={value:raw,updatedAt:Number(localStorage.getItem(`neet-sync-time:${k}`)||0)}});return values};
const writeLocal=(k,raw,time)=>{localStorage.setItem(k,raw);localStorage.setItem(`neet-sync-time:${k}`,String(time||Date.now()))};
(async()=>{try{
 const v='12.17.0';const appMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),authMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-auth.js`),dbMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`);const app=appMod.getApps().length?appMod.getApp():appMod.initializeApp(cfg);const auth=authMod.getAuth(app),db=dbMod.getFirestore(app),provider=new authMod.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});let user=null,syncing=false,timer=null;loginButton.disabled=false;
 const sync=async(manual=false)=>{if(!user||syncing)return;syncing=true;message.textContent='同期中…';let changed=false;try{const ref=dbMod.doc(db,'users',user.uid),snap=await dbMod.getDoc(ref),remote=snap.exists()?(snap.data().storage||{}):{},local=collect(),merged={};for(const key of TRACKED_KEYS){const l=local[key],r=remote[key];if(!l&&!r)continue;if(key==='song-note-songs-v1'||key==='neet-note-lyrics-memos-v1'||key==='neet-note-ideas-v1'){const value=JSON.stringify(mergeArray(l?JSON.parse(l.value):[],r?JSON.parse(r.value):[]));const time=Math.max(l?.updatedAt||0,r?.updatedAt||0,Date.now());merged[key]={value,updatedAt:time};if(!l||l.value!==value){writeLocal(key,value,time);changed=true}}else if(key==='neet-note-calendar-v1'){const value=JSON.stringify(mergeCalendar(l?JSON.parse(l.value):{},r?JSON.parse(r.value):{}));const time=Math.max(l?.updatedAt||0,r?.updatedAt||0,Date.now());merged[key]={value,updatedAt:time};if(!l||l.value!==value){writeLocal(key,value,time);changed=true}}else{const winner=!r||((l?.updatedAt||0)>=(r?.updatedAt||0))?l:r;if(winner){merged[key]=winner;if(!l||l.value!==winner.value){writeLocal(key,winner.value,winner.updatedAt);changed=true}}}}
 await dbMod.setDoc(ref,{storage:merged,songs:merged['song-note-songs-v1']?JSON.parse(merged['song-note-songs-v1'].value):[],email:user.email||'',updatedAt:dbMod.serverTimestamp()},{merge:true});message.textContent='✅ 全機能を同期済み';if(manual)notify('全機能を同期したよ');if(changed&&!sessionStorage.getItem('neet-sync-reloaded')){sessionStorage.setItem('neet-sync-reloaded','1');location.reload()}}catch(e){console.error(e);message.textContent=`同期エラー：${e.code||e.message}`}finally{syncing=false}};
 const originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){originalSet.call(this,k,v);if(this===localStorage&&TRACKED_KEYS.includes(k)){originalSet.call(localStorage,`neet-sync-time:${k}`,String(Date.now()));if(user){clearTimeout(timer);timer=setTimeout(()=>sync(false),900)}}};
 authMod.onAuthStateChanged(auth,async u=>{user=u;if(u){label.textContent='ログイン済み ✓';account.classList.add('show');accountText.textContent=u.email||u.displayName||'Googleアカウント';loginButton.hidden=true;syncButton.hidden=false;logoutButton.hidden=false;message.textContent='ログイン済み。全機能を同期するよ。';await sync(false)}else{label.textContent='ログイン・同期';account.classList.remove('show');loginButton.hidden=false;syncButton.hidden=true;logoutButton.hidden=true;message.textContent='未ログイン。データはこの端末に保存中。'}});
 loginButton.onclick=async()=>{loginButton.disabled=true;try{await authMod.signInWithPopup(auth,provider)}catch(e){message.textContent=`ログインエラー：${e.code||e.message}`;loginButton.disabled=false}};syncButton.onclick=()=>sync(true);logoutButton.onclick=()=>authMod.signOut(auth).then(()=>notify('ログアウトしたよ'));
}catch(e){console.error(e);message.textContent=`読込エラー：${e.message}`}})();
})();