(()=>{
'use strict';
const KEY='song-note-songs-v1',cfg=window.NEET_FIREBASE_CONFIG||{},ready=Boolean(cfg.apiKey&&cfg.authDomain&&cfg.projectId&&cfg.appId),side=document.getElementById('sideMenu');if(!side)return;
const b=document.createElement('button');b.className='menu-link';b.type='button';b.innerHTML='<span class="menu-icon">☁️</span><span>ログイン・同期</span>';side.insertBefore(b,side.querySelector('[data-theme-toggle]')||null);
const style=document.createElement('style');style.textContent='.cloud-toast{position:fixed;left:50%;top:18px;z-index:50000;display:flex;align-items:center;gap:12px;width:min(92vw,430px);padding:15px 18px;border:1px solid rgba(255,255,255,.45);border-radius:18px;background:rgba(28,28,30,.92);color:#fff;box-shadow:0 18px 50px rgba(0,0,0,.28);backdrop-filter:blur(18px);transform:translate(-50%,-140%);opacity:0;transition:.35s cubic-bezier(.2,.8,.2,1);pointer-events:none}.cloud-toast.show{transform:translate(-50%,0);opacity:1}.cloud-toast-icon{display:grid;place-items:center;width:42px;height:42px;flex:0 0 42px;border-radius:50%;background:#34c759;font-size:1.35rem}.cloud-toast-copy b{display:block;font-size:1rem}.cloud-toast-copy small{display:block;margin-top:2px;color:rgba(255,255,255,.75);font-size:.8rem}.cloud-celebrate{position:fixed;inset:0;z-index:49999;pointer-events:none;overflow:hidden}.cloud-spark{position:absolute;top:-20px;font-size:1.3rem;animation:cloudFall 1.5s ease-in forwards}@keyframes cloudFall{to{transform:translateY(105vh) rotate(480deg);opacity:0}}@media(prefers-reduced-motion:reduce){.cloud-toast{transition:none}.cloud-spark{display:none}}';document.head.appendChild(style);
const toast=document.createElement('div');toast.className='cloud-toast';toast.innerHTML='<span class="cloud-toast-icon">✓</span><span class="cloud-toast-copy"><b id="cloudToastTitle">ログインできたよ！</b><small id="cloudToastText">クラウド同期を開始します</small></span>';document.body.appendChild(toast);
let toastTimer=null;const notify=(title,text,celebrate=false)=>{toast.querySelector('#cloudToastTitle').textContent=title;toast.querySelector('#cloudToastText').textContent=text||'';toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);if(celebrate){const layer=document.createElement('div');layer.className='cloud-celebrate';const marks=['✨','♪','★','🎉','☁️'];for(let i=0;i<18;i++){const s=document.createElement('span');s.className='cloud-spark';s.textContent=marks[i%marks.length];s.style.left=`${Math.random()*100}%`;s.style.animationDelay=`${Math.random()*.45}s`;s.style.animationDuration=`${1.1+Math.random()*.8}s`;layer.appendChild(s)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),2400)}};
const box=document.createElement('div');box.style.cssText='position:fixed;inset:0;z-index:32000;display:none;place-items:center;padding:18px;background:rgba(17,24,39,.58)';box.innerHTML='<section style="width:min(430px,100%);padding:22px;border-radius:22px;background:var(--ui-surface,#fffdf8);color:var(--ui-text,#1f2937)"><div style="display:flex;justify-content:space-between;align-items:center"><h2>☁️ クラウド同期</h2><button id="cloudClose" type="button">×</button></div><p id="cloudMessage">曲データを端末間で同期できるよ。</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button id="cloudLogin" class="primary-button" type="button">Googleでログイン</button><button id="cloudSync" class="ghost-button" type="button">今すぐ同期</button><button id="cloudLogout" class="ghost-button" type="button">ログアウト</button></div></section>';document.body.appendChild(box);
const msg=box.querySelector('#cloudMessage'),login=box.querySelector('#cloudLogin'),syncBtn=box.querySelector('#cloudSync'),logout=box.querySelector('#cloudLogout');b.onclick=()=>box.style.display='grid';box.querySelector('#cloudClose').onclick=()=>box.style.display='none';
if(!ready){msg.textContent='Firebase設定がまだ入っていないよ。';login.disabled=syncBtn.disabled=logout.disabled=true;return;}
(async()=>{try{
 const appMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js');
 const authMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js');
 const dbMod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js');
 const app=appMod.initializeApp(cfg),auth=authMod.getAuth(app),db=dbMod.getFirestore(app);let user=null,syncing=false,syncTimer=null,lastUid=sessionStorage.getItem('neet-note-last-auth-uid')||'';
 const provider=new authMod.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});
 const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY));return Array.isArray(v)?v:[]}catch{return[]}};
 const merge=(a,b)=>{const m=new Map();[...a,...b].forEach(x=>{const old=m.get(x.id);if(!old||new Date(x.updatedAt||0)>new Date(old.updatedAt||0))m.set(x.id,x)});return[...m.values()]};
 const sync=async(manual=false)=>{if(!user||syncing)return;syncing=true;msg.textContent='同期中…';try{const ref=dbMod.doc(db,'users',user.uid),snap=await dbMod.getDoc(ref),remote=snap.exists()&&Array.isArray(snap.data().songs)?snap.data().songs:[],songs=merge(read(),remote);localStorage.setItem(KEY,JSON.stringify(songs));await dbMod.setDoc(ref,{songs,updatedAt:dbMod.serverTimestamp()},{merge:true});msg.textContent=`同期済み：${songs.length}曲`;if(manual)notify('同期できたよ！',`${songs.length}曲をクラウドに保存しました`);}catch(e){console.error(e);msg.textContent=`同期エラー：${e.code||e.message}`;}finally{syncing=false}};
 try{await authMod.getRedirectResult(auth)}catch(e){console.error(e);msg.textContent=`ログインエラー：${e.code||e.message}`;}
 authMod.onAuthStateChanged(auth,async u=>{user=u;login.hidden=Boolean(u);logout.hidden=!u;syncBtn.hidden=!u;msg.textContent=u?`${u.email||'Googleアカウント'}でログイン中`:'未ログイン。データはこの端末に保存中。';if(u){if(lastUid!==u.uid){notify('ログインできたよ！',`${u.displayName||u.email||'Googleアカウント'}で接続しました`,true);sessionStorage.setItem('neet-note-last-auth-uid',u.uid);lastUid=u.uid;}await sync();}else{sessionStorage.removeItem('neet-note-last-auth-uid');lastUid='';}});
 login.onclick=async()=>{login.disabled=true;msg.textContent='Googleログインを開いているよ…';try{const mobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)||window.matchMedia('(display-mode: standalone)').matches;if(mobile){await authMod.signInWithRedirect(auth,provider);}else{await authMod.signInWithPopup(auth,provider);}}catch(e){console.error(e);msg.textContent=`ログインエラー：${e.code||e.message}`;login.disabled=false;}};
 logout.onclick=async()=>{await authMod.signOut(auth);notify('ログアウトしたよ','データはこの端末にも残っています');};syncBtn.onclick=()=>sync(true);
 window.addEventListener('storage',e=>{if(e.key===KEY&&user){clearTimeout(syncTimer);syncTimer=setTimeout(sync,800)}});
 document.addEventListener('neet-note:saved',()=>{if(user){clearTimeout(syncTimer);syncTimer=setTimeout(sync,900)}});
}catch(e){console.error(e);msg.textContent=`クラウド機能の読込エラー：${e.message}`;}})();
})();
