(()=>{
'use strict';
const engineURL=new URL('sync-engine.js?v=20260908-restore2',document.currentScript?.src||location.href).href;
const cfg=window.NEET_FIREBASE_CONFIG||{};
const side=document.getElementById('sideMenu');
if(!side||document.getElementById('cloudSyncMenuButton'))return;
const menuButton=document.createElement('button');menuButton.id='cloudSyncMenuButton';menuButton.className='menu-link';menuButton.type='button';menuButton.innerHTML='<span class="menu-icon">☁️</span><span id="cloudMenuLabel">ログイン・同期</span>';side.insertBefore(menuButton,side.querySelector('[data-theme-toggle]')||null);
const style=document.createElement('style');style.textContent='.cloud-modal{position:fixed;inset:0;z-index:32000;display:none;place-items:center;padding:18px;background:rgba(17,24,39,.58)}.cloud-modal.open{display:grid}.cloud-panel{width:min(430px,100%);padding:22px;border-radius:22px;background:var(--ui-surface,#fffdf8);color:var(--ui-text,#1f2937);box-shadow:0 24px 70px rgba(0,0,0,.3)}.cloud-head{display:flex;align-items:center;justify-content:space-between}.cloud-close{width:44px;height:44px;border:0;border-radius:50%;font-size:1.25rem}.cloud-actions{display:flex;gap:10px;flex-wrap:wrap}.cloud-account{display:none;margin:14px 0;padding:14px;border-radius:15px;background:rgba(52,199,89,.12)}.cloud-account.show{display:block}.cloud-toast{position:fixed;left:50%;top:18px;z-index:50000;width:min(92vw,430px);padding:15px 18px;border-radius:18px;background:#1c1c1e;color:#fff;transform:translate(-50%,-150%);opacity:0;transition:.3s}.cloud-toast.show{transform:translate(-50%,0);opacity:1}@media(max-width:600px){.cloud-modal{align-items:end;padding:0}.cloud-panel{border-radius:22px 22px 0 0;padding-bottom:calc(22px + env(safe-area-inset-bottom))}}';document.head.appendChild(style);
const modal=document.createElement('div');modal.className='cloud-modal';modal.innerHTML='<section class="cloud-panel"><div class="cloud-head"><h2>☁️ クラウド同期</h2><button class="cloud-close" type="button">×</button></div><div id="cloudAccount" class="cloud-account"><b>✅ Googleログイン済み</b><small id="cloudAccountText"></small></div><p id="cloudMessage">認証状態を確認中…</p><div class="cloud-actions"><button id="cloudLogin" class="primary-button" type="button" disabled>Googleでログイン</button><button id="cloudSync" class="ghost-button" type="button" hidden>今すぐ同期</button><button id="cloudLogout" class="ghost-button" type="button" hidden>ログアウト</button></div></section>';document.body.appendChild(modal);
const toast=document.createElement('div');toast.className='cloud-toast';document.body.appendChild(toast);let toastTimer;const notify=t=>{toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)};
const label=document.getElementById('cloudMenuLabel'),message=modal.querySelector('#cloudMessage'),account=modal.querySelector('#cloudAccount'),accountText=modal.querySelector('#cloudAccountText'),loginButton=modal.querySelector('#cloudLogin'),syncButton=modal.querySelector('#cloudSync'),logoutButton=modal.querySelector('#cloudLogout');
menuButton.onclick=()=>{modal.classList.add('open');document.body.style.overflow='hidden'};modal.querySelector('.cloud-close').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};
if(!(cfg.apiKey&&cfg.authDomain&&cfg.projectId&&cfg.appId)){message.textContent='Firebase設定が不足しているよ。';return;}
(async()=>{try{
 const v='12.17.0';const appMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),authMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-auth.js`),dbMod=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`);const app=appMod.getApps().length?appMod.getApp():appMod.initializeApp(cfg);const auth=authMod.getAuth(app),db=dbMod.getFirestore(app),provider=new authMod.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});loginButton.disabled=false;
 await (window.__neetSyncEngineLoading ||= new Promise((resolve,reject)=>{if(window.NEETSyncEngine)return resolve();const script=document.createElement('script');script.src=engineURL;script.onload=resolve;script.onerror=reject;document.head.appendChild(script)}));
 const engine=window.NEETSyncEngine.configure(db,dbMod);
 const sync=()=>engine.sync();
 window.addEventListener('neet-note:sync-status',e=>{message.textContent=e.detail.text});
 authMod.onAuthStateChanged(auth,async u=>{if(u){label.textContent='ログイン済み ✓';account.classList.add('show');accountText.textContent=u.email||u.displayName||'Googleアカウント';loginButton.hidden=true;syncButton.hidden=false;logoutButton.hidden=false;message.textContent='ログイン済み。全機能を同期するよ。';await engine.setUser(u)}else{engine.setUser(null);label.textContent='ログイン・同期';account.classList.remove('show');loginButton.hidden=false;syncButton.hidden=true;logoutButton.hidden=true;message.textContent='未ログイン。データはこの端末に保存中。'}});
 loginButton.onclick=async()=>{loginButton.disabled=true;try{await authMod.signInWithPopup(auth,provider)}catch(e){message.textContent=`ログインエラー：${e.code||e.message}`;loginButton.disabled=false}};syncButton.onclick=()=>sync(true);logoutButton.onclick=()=>authMod.signOut(auth).then(()=>notify('ログアウトしたよ'));
}catch(e){console.error(e);message.textContent=`読込エラー：${e.message}`}})();
})();