(()=>{
'use strict';
const root=document.documentElement,meta=document.querySelector('meta[name="theme-color"]'),THEME='neet-note-theme';
const params=new URLSearchParams(location.search),path=location.pathname.replace(/\/index\.html$/,'/'),isHome=/\/NEET-note\/$/.test(path),intro=document.getElementById('neetIntro');
const shouldIntro=isHome&&!params.has('mode')&&!params.has('song')&&!document.referrer.startsWith(`${location.origin}/NEET-note/`)&&sessionStorage.getItem('neet-note-intro-shown')!=='1';
if(intro){if(shouldIntro)sessionStorage.setItem('neet-note-intro-shown','1');else{intro.remove();document.body.style.overflow=''}}
const preferred=()=>{const s=localStorage.getItem(THEME);return s==='light'||s==='dark'?s:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')};
const apply=theme=>{root.dataset.theme=theme;root.style.colorScheme=theme;meta?.setAttribute('content',theme==='dark'?'#141311':'#d9c7a8');document.querySelectorAll('[data-theme-toggle]').forEach(b=>{const d=theme==='dark';b.innerHTML=`<span aria-hidden="true">${d?'☀️':'🌙'}</span><span>${d?'ライトモード':'ダークモード'}</span>`;b.setAttribute('aria-pressed',String(d))})};
apply(preferred());
document.addEventListener('click',e=>{const b=e.target.closest('[data-theme-toggle]');if(!b)return;const n=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem(THEME,n);apply(n)});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',e=>{if(!localStorage.getItem(THEME))apply(e.matches?'dark':'light')});

const side=document.getElementById('sideMenu');
if(side&&!document.getElementById('neetHelpButton')){
 const helpButton=document.createElement('button');helpButton.id='neetHelpButton';helpButton.type='button';helpButton.className='menu-link';helpButton.innerHTML='<span class="menu-icon">❓</span><span>ヘルプ・使い方</span>';
 const theme=side.querySelector('[data-theme-toggle]');side.insertBefore(helpButton,theme||null);
 const style=document.createElement('style');style.textContent=`.neet-help-backdrop{position:fixed;inset:0;z-index:30000;display:none;place-items:center;padding:18px;background:rgba(17,24,39,.58)}.neet-help-backdrop.open{display:grid}.neet-help-dialog{width:min(720px,100%);max-height:84dvh;overflow:auto;padding:20px;background:var(--ui-surface,#fffdf8);color:var(--ui-text,#1f2937);border:1px solid var(--ui-line,#ded6c9);border-radius:20px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.neet-help-head{position:sticky;top:-20px;z-index:1;display:flex;align-items:center;justify-content:space-between;margin:-20px -20px 16px;padding:18px 20px;background:inherit;border-bottom:1px solid var(--ui-line,#ded6c9)}.neet-help-head h2{margin:0;font-size:1.25rem}.neet-help-close{width:38px;height:38px;border:0;border-radius:11px;background:var(--ui-surface-2,#f1f1f1);color:inherit;font-size:1.35rem}.neet-help-intro{color:var(--ui-muted,#6b7280);line-height:1.7}.neet-help-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.neet-help-item{padding:14px;border:1px solid var(--ui-line,#ded6c9);border-radius:14px;background:var(--ui-surface-2,#f7f2e9)}.neet-help-item b{display:block;margin-bottom:5px}.neet-help-item p{margin:0;color:var(--ui-muted,#6b7280);font-size:.88rem;line-height:1.65}@media(max-width:600px){.neet-help-backdrop{align-items:end;padding:0}.neet-help-dialog{max-height:88dvh;border-radius:22px 22px 0 0}.neet-help-grid{grid-template-columns:1fr}}`;
 document.head.appendChild(style);
 const tools=location.pathname.endsWith('/tools.html');
 const data=tools?['作曲・演奏支援ツール',[['コード進行ルーレット','キー・長短・ジャンルを選び、作曲の土台になる進行を生成する。'],['移調・カポ変換','コードを入力し、元のキーと変更先を選んで一括変換する。'],['メトロノーム','BPMと拍子を設定してテンポを確認する。'],['チューナー','マイクを許可し、中央に近づくよう楽器の音程を合わせる。'],['ドラム','スタイルとBPMを選び、簡易リズムを再生する。'],['AI Composer','保存した曲を選び、作曲アシスタントへ引き継ぐ。'],['バックアップ','曲データをJSONで保存・復元する。']]]:['作曲ノート',[['新しい曲','新規ノートを作り、タイトル・作家名・キー・BPMなどを入力する。'],['コード進行メモ','ルート、種類、ベース音を選んでコードを追加する。'],['曲の構成','イントロ、Aメロ、サビなどの流れを記録する。'],['音源・ボイスメモ','録音したアイデアを曲ノートへ添付する。'],['検索','曲名・作家名・雰囲気・コードから保存曲を探す。'],['保存と削除','保存して一覧へ戻る。不要な曲は編集画面から削除する。'],['AIに相談','現在の曲情報を作曲アシスタントへ引き継ぐ。']]];
 const modal=document.createElement('div');modal.className='neet-help-backdrop';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<section class="neet-help-dialog" role="dialog" aria-modal="true"><div class="neet-help-head"><h2>${data[0]}の使い方</h2><button class="neet-help-close" type="button" aria-label="ヘルプを閉じる">×</button></div><p class="neet-help-intro">このページで使える機能をまとめているよ。</p><div class="neet-help-grid">${data[1].map(([t,d])=>`<div class="neet-help-item"><b>${t}</b><p>${d}</p></div>`).join('')}</div></section>`;document.body.appendChild(modal);
 const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''};
 helpButton.onclick=()=>{document.getElementById('sideMenu')?.classList.remove('open');document.getElementById('menuOverlay')?.classList.remove('open');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
 modal.querySelector('.neet-help-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
}

const list=document.getElementById('listView'),toolbar=list?.querySelector('.toolbar');
if(list&&toolbar&&!document.getElementById('homeDashboard')){
 const style=document.createElement('style');style.textContent='.home-dashboard{margin-bottom:24px}.home-welcome{padding:26px;border:1px solid var(--border);border-radius:22px;background:var(--paper);box-shadow:var(--shadow)}.home-welcome h2{margin:0;font-size:clamp(1.55rem,5vw,2.25rem)}.home-welcome p{color:var(--muted);line-height:1.7}.home-actions{display:flex;gap:10px;flex-wrap:wrap}.home-tool-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-top:18px}.home-tool-card{padding:15px;border:1px solid var(--border);border-radius:16px;background:var(--paper);color:var(--text);text-decoration:none;font-weight:800}@media(max-width:760px){.home-tool-grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(style);
 const d=document.createElement('div');d.id='homeDashboard';d.className='home-dashboard';d.innerHTML='<section class="home-welcome"><h2>思いついた音を、すぐ形に。</h2><p>曲の記録からコード・スケール確認まで、ここから音楽制作を始めよう。</p><div class="home-actions"><button id="homeNewSongBtn" class="primary-button">＋ 新しい曲を作る</button><a class="ghost-button" href="tools.html" style="text-decoration:none">🧰 ツールを開く</a></div><div class="home-tool-grid"><a class="home-tool-card" href="https://akito0802.github.io/Cordhyo-/index.html">📚 コード</a><a class="home-tool-card" href="https://akito0802.github.io/scale/">🎸 スケール</a><a class="home-tool-card" href="https://akito0802.github.io/-h/">🎵 指板</a><a class="home-tool-card" href="tools.html">🧰 ツール</a></div></section>';
 list.insertBefore(d,toolbar);document.getElementById('homeNewSongBtn')?.addEventListener('click',()=>document.getElementById('newSongBtn')?.click());
}
})();