(()=>{
'use strict';
const params=new URLSearchParams(location.search);if(params.get('mode')==='note'||params.has('song'))return;
const ROOT='https://akito0802.github.io/NEET-note/';const NEETON=ROOT+'neeton.svg?v=4';
const shell=document.querySelector('.app-shell');if(shell)shell.style.display='none';
document.querySelectorAll('.neet-home,#neetHomeDashboard').forEach(el=>el.remove());
const style=document.createElement('style');style.id='neet-home-final-style';style.textContent=`
:root{--h-bg:#efe4d4;--h-paper:#fffaf1;--h-card:#fffdf8;--h-line:#e1cfb8;--h-text:#3e2b1e;--h-muted:#75614f;--h-accent:#8a5e36}
body{margin:0;background:var(--h-bg)!important;color:var(--h-text);font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif}
.neet-final-home{width:100%;min-height:100dvh;padding:max(14px,env(safe-area-inset-top)) 8px calc(22px + env(safe-area-inset-bottom));box-sizing:border-box}.nf-shell{width:min(100%,560px);margin:0 auto;padding:13px 11px 14px;border:1px solid var(--h-line);border-radius:22px;background:linear-gradient(180deg,#fffaf1,#fbf2e5);box-shadow:0 12px 30px rgba(90,61,32,.1)}
.nf-head{display:grid;grid-template-columns:1fr 58px;align-items:center;padding:2px 7px 12px;border-bottom:1px solid #eadbc8;text-align:center}.nf-head>div{padding-left:58px}.nf-head b{display:block;font-size:1.03rem;letter-spacing:.12em}.nf-head small{display:block;margin-top:4px;font-size:.72rem;font-weight:700}.nf-head img{width:56px;height:56px;object-fit:contain}
.nf-account{display:grid;grid-template-columns:50px 1fr 20px;align-items:center;gap:10px;margin-top:11px;padding:11px;border:1px solid #e3d1bc;border-radius:14px;background:#fffdf8;box-shadow:0 3px 10px rgba(82,54,28,.05)}.nf-avatar{position:relative;display:grid;place-items:center;width:48px;height:48px;border:1px solid #dec8aa;border-radius:50%;background:#f7ecdf}.nf-avatar img{width:41px;height:41px}.nf-avatar i{position:absolute;right:0;bottom:2px;width:11px;height:11px;border:2px solid #fff;border-radius:50%;background:#67b653}.nf-user b,.nf-user span,.nf-user small{display:block}.nf-user b{font-size:.88rem}.nf-user span{margin-top:2px;font-size:.68rem;color:var(--h-muted)}.nf-user small{margin-top:3px;font-size:.64rem;font-weight:750;color:var(--h-muted)}.nf-arrow{font-size:1.3rem;color:#7b593a}
.nf-sync,.nf-row{width:100%;box-sizing:border-box;border:1px solid var(--h-line);background:#fffaf3;color:var(--h-text);font:inherit;font-weight:850}.nf-sync{min-height:48px;margin:10px 0;border-radius:12px;font-size:.83rem}.nf-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.nf-tile{display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:0;min-height:91px;padding:8px 2px;border:1px solid #e2d0bb;border-radius:12px;background:#fffdf8;color:var(--h-text);text-decoration:none;text-align:center;box-shadow:0 3px 9px rgba(82,54,28,.045)}.nf-icon{display:grid;place-items:center;height:29px;margin-bottom:5px;color:#8a5e36;font-family:Georgia,serif;font-size:1.35rem}.nf-tile b{font-size:.61rem;line-height:1.25}.nf-tile small{margin-top:1px;font-size:.51rem;font-weight:700}.nf-row{display:grid;grid-template-columns:34px 1fr 26px;align-items:center;gap:8px;min-height:53px;margin-top:8px;padding:8px 11px;border-radius:12px;text-align:left;text-decoration:none}.nf-row>span:first-child{display:grid;place-items:center;width:31px;height:31px;color:#805a38;font-size:1.35rem}.nf-row b{font-size:.8rem}.nf-row em{justify-self:end;font-style:normal;font-size:1.2rem}.nf-toggle{justify-self:end;width:45px;height:25px;padding:3px;border-radius:999px;background:#b59b79;box-sizing:border-box}.nf-toggle:after{content:'';display:block;width:19px;height:19px;border-radius:50%;background:#fff;transition:.18s}.nf-theme.on .nf-toggle{background:#735032}.nf-theme.on .nf-toggle:after{transform:translateX(20px)}
html[data-theme="dark"] body{background:#211d19!important}html[data-theme="dark"] .nf-shell{background:#2b251f;border-color:#514438;color:#f6eee4}html[data-theme="dark"] .nf-account,html[data-theme="dark"] .nf-sync,html[data-theme="dark"] .nf-tile,html[data-theme="dark"] .nf-row{background:#332b24;border-color:#514438;color:#f6eee4}html[data-theme="dark"] .nf-user span,html[data-theme="dark"] .nf-user small{color:#c8b8a4}
@media(min-width:600px){.nf-shell{padding:18px}.nf-grid{gap:9px}.nf-tile{min-height:108px}.nf-tile b{font-size:.7rem}.nf-tile small{font-size:.58rem}}
`;document.head.appendChild(style);
const items=[[ROOT+'?mode=note','▤','ノート'],[ROOT+'lyrics.html','♬','歌詞メモ'],[ROOT+'voice-memo.html','♩','ボイスメモ','（録音）'],[ROOT+'ideas.html','♧','アイデアメモ'],[ROOT+'tools.html','⌘','制作ツール'],[ROOT+'calendar.html','▣','制作カレンダー'],[ROOT+'melody.html','♪','メロディ入力'],[ROOT+'theory-assist.html','✣','理論アシスト'],[ROOT+'theory-library.html','▥','統合理論','ライブラリ'],['https://akito0802.github.io/Cordhyo-/','♮','コード辞典'],['https://akito0802.github.io/scale/','♯','スケール辞典'],['https://akito0802.github.io/-h/','♯','指板']];
const home=document.createElement('main');home.className='neet-final-home';home.innerHTML=`<section class="nf-shell"><header class="nf-head"><div><b>NEETNOTE</b><small>音楽と、いつまでも。</small></div><img src="${NEETON}" alt="ニートン"></header><section class="nf-account"><div class="nf-avatar"><img src="${NEETON}" alt="ニートン"><i></i></div><div class="nf-user"><b>ニートン</b><span>未ログイン</span><small>この端末に保存中</small></div><span class="nf-arrow">›</span></section><button class="nf-sync" id="nfSync" type="button">♧　ログイン・同期</button><nav class="nf-grid">${items.map(([href,icon,label,sub])=>`<a class="nf-tile" href="${href}"><span class="nf-icon">${icon}</span><b>${label}</b>${sub?`<small>${sub}</small>`:''}</a>`).join('')}</nav><a class="nf-row" href="${ROOT}neeton-home.html"><span>⌂</span><b>ニートンのおうち</b><em></em></a><button class="nf-row nf-theme" id="nfTheme" type="button"><span>☾</span><b>ダークモード</b><i class="nf-toggle"></i></button><button class="nf-row" id="nfHelp" type="button"><span>?</span><b>ヘルプ・使い方</b><em>›</em></button></section>`;document.body.insertBefore(home,document.body.firstChild);
const theme=document.getElementById('nfTheme');const apply=t=>{document.documentElement.dataset.theme=t;theme.classList.toggle('on',t==='dark')};apply(localStorage.getItem('neet-note-theme')==='dark'?'dark':'light');theme.onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('neet-note-theme',t);apply(t)};document.getElementById('nfHelp').onclick=()=>alert('各カードからNEETNOTEの機能へ移動できるよ。');document.getElementById('nfSync').onclick=()=>{const b=document.querySelector('.ngm-btn,.n4-trigger,.neet-menu-hamburger');if(b)b.click()};
})();