(()=>{
'use strict';
const params=new URLSearchParams(location.search);
if(params.get('mode')==='note'||params.has('song'))return;
const ROOT='https://akito0802.github.io/NEET-note/';
const shell=document.querySelector('.app-shell');
if(shell)shell.style.display='none';
const style=document.createElement('style');
style.textContent=`
:root{--home-bg:#d9c7a8;--home-paper:#fffaf2;--home-card:#fffdf8;--home-line:#dfd1bd;--home-text:#30251c;--home-muted:#7a6a59;--home-accent:#9a6c3a;--home-soft:#f3eadc;--home-shadow:0 18px 42px rgba(83,58,30,.12)}
body{background:linear-gradient(180deg,#d9c7a8 0%,#e6d8c1 100%)!important}
.neet-home{width:min(1080px,calc(100% - 28px));margin:0 auto;padding:24px 0 56px;font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif;color:var(--home-text)}
.neet-home-top{display:flex;justify-content:space-between;align-items:center;gap:14px;margin:4px 0 18px;padding-left:62px}.neet-home-brand small{display:block;color:#7f6b56;font-size:.68rem;font-weight:900;letter-spacing:.18em}.neet-home-brand h1{margin:3px 0 0;font-size:clamp(1.7rem,5vw,2.7rem);letter-spacing:-.04em}.neet-home-mini{padding:8px 11px;border:1px solid rgba(115,83,50,.16);border-radius:999px;background:rgba(255,250,242,.55);font-size:.72rem;font-weight:800;color:#72563a}
.neet-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:1.5fr .7fr;gap:22px;align-items:center;padding:28px;border:1px solid var(--home-line);border-radius:28px;background:linear-gradient(135deg,#fffaf2,#f8eedf);box-shadow:var(--home-shadow)}.neet-hero-copy p{margin:0;color:var(--home-muted);font-size:.9rem;line-height:1.8}.neet-hero-copy h2{margin:5px 0 10px;font-size:clamp(1.65rem,4vw,2.7rem);line-height:1.16;letter-spacing:-.045em}.neet-hero-copy h2 span{color:#8c5f30}.neet-hero-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:17px}.neet-primary,.neet-secondary{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 15px;border-radius:13px;text-decoration:none;font-weight:900;font-size:.82rem}.neet-primary{background:#8f6335;color:#fff;border:1px solid #8f6335;box-shadow:0 7px 18px rgba(99,67,33,.18)}.neet-secondary{background:#fffaf3;color:#654627;border:1px solid var(--home-line)}.neet-hero-mascot{display:grid;place-items:center;min-height:180px}.neet-hero-mascot img{width:min(180px,70%);filter:drop-shadow(0 12px 20px rgba(83,58,30,.14))}
.neet-section{margin-top:18px}.neet-section-head{display:flex;justify-content:space-between;align-items:end;gap:10px;margin:0 2px 9px}.neet-section-head h3{margin:0;font-size:1rem}.neet-section-head span{color:var(--home-muted);font-size:.72rem}.neet-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.neet-card{position:relative;display:flex;flex-direction:column;gap:9px;min-height:126px;padding:15px;border:1px solid var(--home-line);border-radius:18px;background:rgba(255,253,248,.92);color:inherit;text-decoration:none;box-shadow:0 8px 20px rgba(83,58,30,.06);transition:.16s transform,.16s box-shadow}.neet-card:hover{transform:translateY(-2px);box-shadow:0 12px 24px rgba(83,58,30,.1)}.neet-card-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#f4e7d5;font-size:1.15rem}.neet-card b{font-size:.87rem}.neet-card small{color:var(--home-muted);font-size:.69rem;line-height:1.55}.neet-card-arrow{position:absolute;right:13px;top:13px;color:#a08c73}
.neet-lower{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:18px}.neet-panel{padding:17px;border:1px solid var(--home-line);border-radius:20px;background:rgba(255,250,242,.86);box-shadow:0 8px 20px rgba(83,58,30,.05)}.neet-panel h3{margin:0 0 11px;font-size:.95rem}.neet-recent{display:grid;gap:7px}.neet-recent-item{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 11px;border-radius:12px;background:#fffdf8;border:1px solid #e7daca}.neet-recent-copy{min-width:0}.neet-recent-copy b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.79rem}.neet-recent-copy small{display:block;margin-top:3px;color:var(--home-muted);font-size:.67rem}.neet-count{font-size:1.9rem;font-weight:950;letter-spacing:-.04em;color:#80582f}.neet-tip{margin-top:8px;color:var(--home-muted);font-size:.72rem;line-height:1.7}.neet-footer{text-align:center;margin-top:28px;color:#897763;font-size:.65rem;letter-spacing:.12em}
html[data-theme="dark"] body{background:#211d19!important}html[data-theme="dark"] .neet-home{--home-paper:#2b251f;--home-card:#302922;--home-line:#514438;--home-text:#f6eee4;--home-muted:#c1b19e;--home-accent:#d3a56b;--home-soft:#3a3027}.neet-card,.neet-panel,.neet-hero{color:var(--home-text)}html[data-theme="dark"] .neet-card,html[data-theme="dark"] .neet-panel,html[data-theme="dark"] .neet-recent-item{background:#2f2922}html[data-theme="dark"] .neet-hero{background:linear-gradient(135deg,#302922,#27221d)}html[data-theme="dark"] .neet-card-icon{background:#3b3027}
@media(max-width:780px){.neet-home{width:calc(100% - 14px);padding-top:10px}.neet-home-top{padding-left:54px;margin-bottom:10px}.neet-home-mini{display:none}.neet-hero{grid-template-columns:1fr;padding:18px;border-radius:22px}.neet-hero-mascot{position:absolute;right:-15px;bottom:-18px;min-height:0;opacity:.22}.neet-hero-mascot img{width:150px}.neet-hero-copy{position:relative;z-index:1;padding-right:18px}.neet-grid{grid-template-columns:repeat(2,1fr);gap:8px}.neet-card{min-height:118px;padding:13px}.neet-lower{grid-template-columns:1fr}.neet-section{margin-top:14px}.neet-primary,.neet-secondary{flex:1;min-width:130px}.neet-footer{padding-bottom:env(safe-area-inset-bottom)}}
`;
document.head.appendChild(style);
let songs=[];try{songs=JSON.parse(localStorage.getItem('song-note-songs-v1')||'[]');if(!Array.isArray(songs))songs=[]}catch{songs=[]}
const recent=songs.slice().sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0)).slice(0,3);
const cards=[
 [ROOT+'?mode=note','📝','曲ノート','曲の構成・コード・制作情報をまとめる'],
 [ROOT+'ideas.html','💡','アイデアメモ','浮かんだ発想をすぐ保存'],
 [ROOT+'lyrics.html','🎤','歌詞メモ','言葉やフレーズをストック'],
 [ROOT+'voice-memo.html','🎙️','ボイスメモ','メロディや演奏を録音'],
 [ROOT+'theory-assist.html','🧠','理論アシスト','コードやスケールを理論から確認'],
 [ROOT+'theory-library.html','📖','統合理論ライブラリ','理論を体系的に読む'],
 ['https://akito0802.github.io/Cordhyo-/','🎸','コード辞典','フォームとコードを探す'],
 ['https://akito0802.github.io/-h/','🎵','指板','スケールを指板で確認']
];
const home=document.createElement('main');home.className='neet-home';home.innerHTML=`
<header class="neet-home-top"><div class="neet-home-brand"><small>COMPOSITION NOTE</small><h1>NEET NOTE</h1></div><span class="neet-home-mini">音楽と、いつまでも。</span></header>
<section class="neet-hero"><div class="neet-hero-copy"><p>作る・残す・学ぶを、ひとつの場所に。</p><h2>今日の音楽を、<br><span>ここから始めよう。</span></h2><p>曲作りのメモから理論確認まで、必要な機能にすぐアクセスできるホーム。</p><div class="neet-hero-actions"><a class="neet-primary" href="${ROOT}?mode=note">📝 曲ノートを開く</a><a class="neet-secondary" href="${ROOT}ideas.html">💡 アイデアを残す</a></div></div><div class="neet-hero-mascot"><img src="${ROOT}neeton.svg?v=4" alt="ニートン"></div></section>
<section class="neet-section"><div class="neet-section-head"><h3>クイックアクセス</h3><span>よく使う機能</span></div><div class="neet-grid">${cards.map(([href,icon,title,desc])=>`<a class="neet-card" href="${href}"><span class="neet-card-arrow">›</span><span class="neet-card-icon">${icon}</span><b>${title}</b><small>${desc}</small></a>`).join('')}</div></section>
<div class="neet-lower"><section class="neet-panel"><h3>最近の曲</h3><div class="neet-recent">${recent.length?recent.map(s=>`<a class="neet-recent-item" href="${ROOT}?mode=note"><span class="neet-recent-copy"><b>${(s.title||'無題の曲').replace(/[&<>]/g,'')}</b><small>${[s.key&&'Key '+s.key,s.bpm&&s.bpm+' BPM'].filter(Boolean).join(' · ')||'作品情報未設定'}</small></span><span>›</span></a>`).join(''):'<div class="neet-recent-item"><span class="neet-recent-copy"><b>まだ曲がないよ</b><small>最初の1曲を作ってみよう</small></span><span>♪</span></div>'}</div></section><section class="neet-panel"><h3>制作ライブラリ</h3><div class="neet-count">${songs.length}</div><div class="neet-tip">保存されている曲ノート数。曲作り・歌詞・理論を行き来しながら、NEETNOTEの中で制作をつなげられるよ。</div></section></div>
<div class="neet-footer">NEETNOTE × NEETON</div>`;
document.body.insertBefore(home,document.body.firstChild);
})();