(()=>{'use strict';
const KEY='neet-note-ideas-v1';const list=document.getElementById('ideaList'),search=document.getElementById('ideaSearch'),empty=document.getElementById('ideaEmpty'),editor=document.getElementById('ideaEditor'),title=document.getElementById('ideaTitle'),category=document.getElementById('ideaCategory'),text=document.getElementById('ideaText'),favorite=document.getElementById('ideaFavorite'),status=document.getElementById('ideaStatus');let ideas=load(),currentId='',timer;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:[]}catch{return[]}}function saveAll(){localStorage.setItem(KEY,JSON.stringify(ideas))}function id(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=search.value.trim().toLowerCase();const rows=ideas.slice().sort((a,b)=>(b.favorite-a.favorite)||new Date(b.updatedAt)-new Date(a.updatedAt)).filter(x=>[x.title,x.text,x.category].join(' ').toLowerCase().includes(q));list.innerHTML=rows.length?'':'<div style="padding:16px;text-align:center;color:var(--muted)">まだアイデアがないよ。</div>';rows.forEach(x=>{const b=document.createElement('button');b.className='idea-item'+(x.id===currentId?' active':'');b.innerHTML=`<b>${x.favorite?'★ ':''}${esc(x.title||'無題のアイデア')}</b><small>${esc(x.category||'その他')}</small>`;b.onclick=()=>select(x.id);list.appendChild(b)})}
function make(){saveNow();const now=new Date().toISOString(),x={id:id(),title:'',category:'曲名',text:'',favorite:false,createdAt:now,updatedAt:now};ideas.unshift(x);saveAll();select(x.id);title.focus()}
function select(i){saveNow();const x=ideas.find(v=>v.id===i);if(!x)return;currentId=i;title.value=x.title||'';category.value=x.category||'その他';text.value=x.text||'';favorite.checked=!!x.favorite;empty.hidden=true;editor.hidden=false;status.textContent='保存済み';render()}
function schedule(){if(!currentId)return;status.textContent='保存中…';clearTimeout(timer);timer=setTimeout(saveNow,350)}function saveNow(){clearTimeout(timer);if(!currentId)return;const i=ideas.findIndex(v=>v.id===currentId);if(i<0)return;ideas[i]={...ideas[i],title:title.value.trim(),category:category.value,text:text.value,favorite:favorite.checked,updatedAt:new Date().toISOString()};saveAll();status.textContent='保存済み';render()}
function remove(){if(!currentId||!confirm('このアイデアを削除しますか？'))return;ideas=ideas.filter(v=>v.id!==currentId);saveAll();currentId='';editor.hidden=true;empty.hidden=false;render();if(ideas.length)select(ideas[0].id)}
[title,category,text,favorite].forEach(x=>{x.addEventListener('input',schedule);x.addEventListener('change',schedule)});search.oninput=render;document.getElementById('newIdeaBtn').onclick=make;document.getElementById('deleteIdea').onclick=remove;document.getElementById('copyIdea').onclick=async()=>{try{await navigator.clipboard.writeText(`${title.value}\n\n${text.value}`);status.textContent='コピーしたよ';setTimeout(()=>status.textContent='保存済み',1200)}catch{alert('コピーできなかったよ。')}};window.addEventListener('beforeunload',saveNow);render();if(ideas.length)select(ideas[0].id);
})();