(()=>{
'use strict';
const STORAGE_KEY='song-note-songs-v1';
const list=document.getElementById('lyricsSongList'),search=document.getElementById('lyricsSearch'),empty=document.getElementById('lyricsEmpty'),workspace=document.getElementById('lyricsWorkspace'),title=document.getElementById('lyricsTitle'),text=document.getElementById('lyricsText'),count=document.getElementById('lyricsCount'),status=document.getElementById('lyricsStatus'),openSong=document.getElementById('openSong');
let songs=loadSongs(),currentId='',timer=null;
function loadSongs(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(value)?value:[]}catch{return[]}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(songs));window.dispatchEvent(new CustomEvent('neet-note-songs-updated',{detail:{songs}}))}
function lyricsOf(song){return song?.lyricIdea??song?.lyrics??''}
function updateCount(){count.textContent=`${text.value.length}文字`}
function render(){const q=search.value.trim().toLowerCase();const filtered=songs.slice().sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(song=>[song.title,song.artist,lyricsOf(song)].join(' ').toLowerCase().includes(q));list.innerHTML='';if(!songs.length){list.innerHTML='<div style="padding:18px;text-align:center;color:var(--muted,#6b7280)">まだ曲がないよ。<br><a href="./?mode=note">ノートで曲を作成</a></div>';return}if(!filtered.length){list.innerHTML='<div style="padding:18px;text-align:center;color:var(--muted,#6b7280)">見つからなかったよ。</div>';return}filtered.forEach(song=>{const button=document.createElement('button');button.type='button';button.className='lyrics-song'+(song.id===currentId?' active':'');button.innerHTML=`<b>${escapeHtml(song.title||'無題の曲')}</b><small>${escapeHtml(song.artist||'アーティスト未設定')} · ${lyricsOf(song).length}文字</small>`;button.onclick=()=>selectSong(song.id);list.appendChild(button)})}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function selectSong(id){saveNow();const song=songs.find(item=>item.id===id);if(!song)return;currentId=id;title.textContent=song.title||'無題の曲';text.value=lyricsOf(song);openSong.href=`./?mode=note&song=${encodeURIComponent(song.id)}`;empty.hidden=true;workspace.hidden=false;status.textContent='保存済み';updateCount();render();text.focus()}
function scheduleSave(){status.textContent='保存中…';clearTimeout(timer);timer=setTimeout(saveNow,400)}
function saveNow(){clearTimeout(timer);if(!currentId)return;const index=songs.findIndex(song=>song.id===currentId);if(index<0)return;songs[index]={...songs[index],lyricIdea:text.value,lyrics:text.value,updatedAt:new Date().toISOString()};persist();status.textContent='保存済み';render()}
function insertSection(){const sections=['【Aメロ】','【Bメロ】','【サビ】','【Cメロ】','【イントロ】','【アウトロ】'];const choice=prompt(`追加するセクション名を入力してね。\n例：${sections.join('、')}`,'【Aメロ】');if(!choice)return;const start=text.selectionStart,end=text.selectionEnd,before=text.value.slice(0,start),after=text.value.slice(end),prefix=before&&!before.endsWith('\n')?'\n\n':'';text.value=before+prefix+choice+'\n'+after;const caret=(before+prefix+choice+'\n').length;text.setSelectionRange(caret,caret);text.focus();updateCount();scheduleSave()}
async function copyLyrics(){try{await navigator.clipboard.writeText(text.value);status.textContent='歌詞をコピーしたよ';setTimeout(()=>status.textContent='保存済み',1300)}catch{alert('コピーできなかったよ。歌詞を長押ししてコピーしてね。')}}
text.addEventListener('input',()=>{updateCount();scheduleSave()});search.addEventListener('input',render);document.getElementById('insertSection').addEventListener('click',insertSection);document.getElementById('copyLyrics').addEventListener('click',copyLyrics);window.addEventListener('beforeunload',saveNow);window.addEventListener('storage',()=>{songs=loadSongs();render()});
render();
const requested=new URLSearchParams(location.search).get('song');if(requested&&songs.some(song=>song.id===requested))selectSong(requested);else if(songs.length)selectSong(songs[0].id);
})();
