(()=>{
'use strict';
const T=window.NEETTheory;
if(!T)return;
const $=id=>document.getElementById(id);
let level='all';let purpose='all';let selectedId=null;

const lessons=[
{id:'what-is-modulation',level:1,cat:'基本',accent:'green',title:'転調とは？',difficulty:'★☆☆☆☆',summary:'曲の「家」に聞こえる主音・キーが途中で変わること。',easy:'Cメジャーで進んでいた曲が、途中からGメジャーを「帰る場所」に感じるようになったら転調。',advanced:'新しい調の主音が機能的に確立し、属機能や終止などによって一時的な色付け以上の調性感が形成された状態。',route:['C','D7','G'],from:'C',to:'G',tags:['基礎','初心者']},
{id:'tonicization',level:1,cat:'基本',accent:'blue',title:'転調とトニック化の違い',difficulty:'★★☆☆☆',summary:'一瞬だけ別コードを主役にするのか、本当に新しいキーへ移るのかを区別する。',easy:'D7→Gが一瞬だけ出てすぐCに戻るなら「Gを少し目立たせた」だけ。Gの世界が続けば転調。',advanced:'セカンダリードミナント等で一時的に特定度数を主音化する tonicization と、持続的な key center の変更を区別する。',route:['C','D7','G','C'],from:'C',to:'G',tags:['基礎','属機能']},
{id:'dominant',level:1,cat:'基本',accent:'yellow',title:'V7が新しいキーを決める',difficulty:'★★☆☆☆',summary:'到着調のV7を置くと、新しい主音を強く予告できる。',easy:'Gへ行きたいなら、その前にD7を鳴らす。D7は「次はGだよ」と強く聞こえる。',advanced:'属七の3rdと7thが形成するトライトーンの解決によって、到着調のIを明確化する最も基本的な転調手段。',route:['C','D7','G'],from:'C',to:'G',tags:['ドミナント','基本技法']},
{id:'related-keys',level:1,cat:'基本',accent:'green',title:'近親調と五度圏',difficulty:'★★☆☆☆',summary:'共通音や共通コードが多いキーほど自然につながりやすい。',easy:'CとG、CとF、CとAmは使う音がよく似ているので移りやすい。',advanced:'調号差・五度圏距離・ダイアトニックコード共有率を、転調の近接性を見る目安として扱う。',route:['C','Am','D7','G'],from:'C',to:'G',tags:['五度圏','近親調']},
{id:'pivot',level:2,cat:'基本技法',accent:'green',title:'共通コード（ピボット）転調',difficulty:'★★☆☆☆',summary:'両方のキーに入るコードを「橋」として読み替える。',easy:'C→GならAmはCではvi、Gではii。Amを境目にしてGの世界へ移れる。',advanced:'pivot chord を旧調と新調の双方のダイアトニック機能で解釈し、後続の属機能で新調を確定する。',route:['C','Am7','D7','G'],from:'C',to:'G',tags:['ピボット','自然']},
{id:'relative',level:2,cat:'基本技法',accent:'blue',title:'平行調・関係調への転調',difficulty:'★☆☆☆☆',summary:'長調と関係短調は構成音を共有しやすく、自然な色変化を作れる。',easy:'CメジャーとAmは同じ白鍵中心。明るいCから少し暗いAmへ自然に移れる。',advanced:'relative major/minor は調号を共有するため共通和音が多く、主音中心の再解釈によって穏やかな転調が可能。',route:['C','G','Am'],from:'C',to:'Am',tags:['関係調','自然']},
{id:'parallel',level:2,cat:'基本技法',accent:'rose',title:'同主調への転調',difficulty:'★★☆☆☆',summary:'主音は同じまま、長調と短調を入れ替える。',easy:'Cメジャー→Cマイナーなら「ド」は同じ家のまま、部屋の色だけ暗く変わる感じ。',advanced:'parallel major/minor 間では主音を保持しつつ3rd・6th・7thの変化によりモードカラーを大きく変えられる。',route:['C','Cm'],from:'C',to:'Cm',tags:['同主調','色変化']},
{id:'secondary-dominant',level:2,cat:'基本技法',accent:'yellow',title:'セカンダリードミナントから転調',difficulty:'★★★☆☆',summary:'V/xを一時的な飾りで終わらせず、そのまま新キーの属機能へ発展させる。',easy:'Cの中でD7を使うとGが目立つ。そのままGの曲として続ければ転調になる。',advanced:'secondary dominant による tonicization を延長し、対象和音を新たな tonic として再定義する。',route:['C','D7','G','Em','Am','D7','G'],from:'C',to:'G',tags:['V/x','属機能']},
{id:'direct',level:2,cat:'基本技法',accent:'rose',title:'直接転調',difficulty:'★☆☆☆☆',summary:'橋を作らず、そのまま別キーへ切り替える。',easy:'Cのサビが終わった瞬間にD♭のラスサビへ。派手で分かりやすい。',advanced:'pivotや属準備を用いず新調へ移行する abrupt/direct modulation。編曲・メロディ・音域上の演出が重要。',route:['C','Db'],from:'C',to:'Db',tags:['直接転調','ラスサビ']},
{id:'common-tone',level:3,cat:'応用技法',accent:'green',title:'共通音（コモントーン）転調',difficulty:'★★★☆☆',summary:'コードではなく1つの音を橋として残す。',easy:'CからEへ行くとき、Eの音をずっと鳴らしておくと別キーへ移っても耳がつながりやすい。',advanced:'common-tone modulation は持続音を旧調と新調で異なる和声音・テンションとして再解釈する。',route:['Cmaj7','Am/E','B7/E','E'],from:'C',to:'E',tags:['共通音','トップノート']},
{id:'modal-interchange',level:3,cat:'応用技法',accent:'blue',title:'モーダルインターチェンジ経由',difficulty:'★★★☆☆',summary:'平行モードから借りたコードを転調の入口にする。',easy:'Cで突然Fmを使うと色が変わる。そのFmをきっかけにE♭へ向かう。',advanced:'borrowed chord の機能を新調側へ再解釈し、♭III・iv・♭VI・♭VIIなどを接続点として使う。',route:['C','Fm','Bb7','Eb'],from:'C',to:'Eb',tags:['借用和音','モード']},
{id:'diminished',level:3,cat:'応用技法',accent:'rose',title:'dim7を使った転調',difficulty:'★★★★☆',summary:'dim7の対称構造と異名同音を使って、複数方向へ進める。',easy:'dim7は同じ形を3半音ずらしても構成音が同じ。だから出口を変えやすい。',advanced:'fully diminished seventh の短3度対称性と leading-tone function の再解釈を利用して遠隔調へ接続する。',route:['C','C#dim7','Dm','G7','C'],from:'C',to:'Dm',tags:['dim7','異名同音']},
{id:'augmented',level:3,cat:'応用技法',accent:'yellow',title:'augコードを使った転調',difficulty:'★★★★☆',summary:'augの長3度対称性を利用して、曖昧な浮遊感から別キーへ移る。',easy:'augは「どこへ行くか決まっていない」感じが強く、着地点を変えやすい。',advanced:'augmented triad の長3度対称性を利用し、構成音を新たな導音・コードトーンとして再解釈する。',route:['C','Caug','E'],from:'C',to:'E',tags:['aug','対称和音']},
{id:'chromatic-mediant',level:3,cat:'応用技法',accent:'rose',title:'クロマティック・メディアント',difficulty:'★★★★☆',summary:'3度関係の遠いキーへ、映画的・劇的に移る。',easy:'CからEやE♭へ行くと、近いようで急に景色が変わる。映画っぽい転調。',advanced:'同質または異質の三和音主音が長3度/短3度離れ、調号差が大きい関係。common tone と chromatic voice leading が接続の鍵。',route:['C','E'],from:'C',to:'E',tags:['映画的','3度関係']},
{id:'enharmonic',level:3,cat:'応用技法',accent:'blue',title:'異名同音転調',difficulty:'★★★★★',summary:'同じ音を別の名前・機能として読み替えて遠いキーへ移る。',easy:'同じ鍵盤でもG#とA♭は名前を変えると、別のキーの一員として考えられる。',advanced:'enharmonic reinterpretation により増6・dim7等の構成音を別機能へ読み替え、調的距離の大きい転調を成立させる。',route:['C','Ab7','Db'],from:'C',to:'Db',tags:['異名同音','上級']},
{id:'sequence',level:3,cat:'応用技法',accent:'green',title:'シーケンス転調',difficulty:'★★★☆☆',summary:'同じパターンを繰り返しながら、段階的に別キーへ進む。',easy:'同じコードの形を1段ずつ上げていくと、自然に景色が変わっていく。',advanced:'harmonic sequence により局所的な機能進行を反復し、tonal center を連続的に移動させる。',route:['C','Dm','G','Am','D','G'],from:'C',to:'G',tags:['シーケンス','段階転調']},
{id:'semitone-up',level:4,cat:'実践',accent:'yellow',title:'ラスサビを半音上げる',difficulty:'★★☆☆☆',summary:'最も分かりやすく高揚感を作れるポップス定番。',easy:'Cのサビを最後だけD♭にすると、一気に持ち上がった感じが出る。',advanced:'直接転調または到着調V7を短く挿入。ボーカル音域とトップノートの連続性を必ず確認する。',route:['C','Ab7','Db'],from:'C',to:'Db',tags:['ラスサビ','半音上']},
{id:'whole-step-up',level:4,cat:'実践',accent:'blue',title:'ラスサビを全音上げる',difficulty:'★★☆☆☆',summary:'半音上より大きく、明確なスケールアップ感を作る。',easy:'CのサビをDへ。高揚感は強いが、歌の最高音も全音上がる。',advanced:'V/V的な橋や直接転調を利用。旋律レンジ・ギターカポ・鍵盤ボイシングの再配置も考慮する。',route:['C','A7','D'],from:'C',to:'D',tags:['ラスサビ','全音上']},
{id:'dark-to-bright',level:4,cat:'実践',accent:'green',title:'暗いAメロ → 明るいサビ',difficulty:'★★☆☆☆',summary:'マイナーから関係長調へ移し、同じ音材料のまま明るくする。',easy:'AmのAメロからCのサビへ行けば、使う音は似たまま雰囲気を明るくできる。',advanced:'relative major への重心移動。属機能G7や共通和音を使いCのtonicを明確化する。',route:['Am','Dm','G7','C'],from:'Am',to:'C',tags:['サビ','明暗']},
{id:'smooth-pop',level:4,cat:'実践',accent:'green',title:'自然にGメジャーへ移りたい',difficulty:'★★☆☆☆',summary:'ピボット＋V7の王道パターンで、違和感を最小化する。',easy:'C→Am7→D7→G。Am7が橋、D7が「次はG」と知らせる。',advanced:'C: vi7 を G: ii7 に読み替え、ii7-V7-I を形成して新調を確立する。',route:['C','Am7','D7','G'],from:'C',to:'G',tags:['ポップス','自然']}
];

const quiz=[
{q:'C major → G major でピボットに使いやすいコードは？',choices:['Am','C#','F#'],answer:0,why:'AmはCではvi、Gではiiとして両方の調に入ります。'},
{q:'G majorを強く確定させる直前のV7は？',choices:['C7','D7','A7'],answer:1,why:'Gの完全5度上はD。D7→Gで属→主の解決になります。'},
{q:'「一瞬だけGを主役にして、すぐCへ戻る」に近いのは？',choices:['トニック化','完全な転調','同主調'],answer:0,why:'一時的な主音化なら tonicization と考える方が自然です。'},
{q:'C major → C minor は何関係？',choices:['関係調','同主調','属調'],answer:1,why:'主音Cを共有したまま長短を入れ替えるので同主調です。'},
{q:'クロマティック・メディアントらしい例は？',choices:['C→G','C→F','C→E'],answer:2,why:'CとEは主音が長3度関係で、共通音を持ちながら調号差が大きい典型です。'}
];

function playRoute(route){route.forEach((name,i)=>{const ch=T.parseChord(name);if(ch)T.playChord(ch,i*.68)})}
function routeHref(item){return `modulation-route.html?from=${encodeURIComponent(item.from)}&to=${encodeURIComponent(item.to)}`}
function lessonCard(item){return `<article class="ml-card" data-accent="${item.accent}" data-id="${item.id}"><div class="ml-card-top"><span>LEVEL ${item.level} / ${item.cat}</span><span class="ml-difficulty">${item.difficulty}</span></div><h3>${item.title}</h3><p>${item.summary}</p><div class="ml-chips">${item.tags.map(x=>`<span class="ml-chip">${x}</span>`).join('')}</div><div class="ml-card-actions"><button class="ml-small-btn primary" type="button" data-detail="${item.id}">詳しく学ぶ</button><button class="ml-small-btn" type="button" data-play="${item.id}">▶ 鳴らす</button><a class="ml-small-btn" href="${routeHref(item)}">ルートで試す</a></div></article>`}
function filteredLessons(){const q=$('search').value.trim().toLowerCase();return lessons.filter(x=>(level==='all'||x.level===Number(level))&&(purpose==='all'||x.tags.includes(purpose)||x.cat===purpose)&&(!q||[x.title,x.summary,x.easy,x.advanced,...x.tags].join(' ').toLowerCase().includes(q)))}
function renderList(){const list=filteredLessons();$('count').textContent=`${list.length} lessons`;$('lessonGrid').innerHTML=list.length?list.map(lessonCard).join(''):'<div class="ml-no-results">条件に合う項目がありません。</div>';document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const item=lessons.find(x=>x.id===b.dataset.play);if(item)playRoute(item.route)})}
function showDetail(id){const item=lessons.find(x=>x.id===id);if(!item)return;selectedId=id;$('detail').innerHTML=`<div class="ml-card-top"><span>LEVEL ${item.level} / ${item.cat}</span><span class="ml-difficulty">${item.difficulty}</span></div><h2>${item.title}</h2><p class="lead">${item.summary}</p><div class="ml-explain"><b>やさしく言うと</b><p>${item.easy}</p></div><div class="ml-explain"><b>理論的には</b><p>${item.advanced}</p></div><div class="ml-route">${item.route.join(' → ')}</div><div class="ml-detail-actions"><button class="ml-btn primary" id="detailPlay" type="button">▶ 例を鳴らす</button><a class="ml-btn" href="${routeHref(item)}">ルートメーカーで試す</a></div>`;$('detailPlay').onclick=()=>playRoute(item.route);history.replaceState(null,'',`?lesson=${encodeURIComponent(id)}`);if(innerWidth<900)$('detail').scrollIntoView({behavior:'smooth',block:'start'})}
function renderPurpose(){document.querySelectorAll('[data-purpose]').forEach(b=>b.classList.toggle('active',b.dataset.purpose===purpose))}
function renderQuiz(){const host=$('quiz');host.innerHTML=quiz.map((x,i)=>`<article class="ml-quiz-card"><h3>Q${i+1}. ${x.q}</h3><div class="ml-choice">${x.choices.map((c,j)=>`<button type="button" data-q="${i}" data-a="${j}">${c}</button>`).join('')}</div><div class="ml-feedback" id="feedback${i}">答えを選んでください。</div></article>`).join('');host.querySelectorAll('[data-q]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.q),a=Number(btn.dataset.a),q=quiz[i];host.querySelectorAll(`[data-q="${i}"]`).forEach(b=>{b.disabled=true;const ai=Number(b.dataset.a);if(ai===q.answer)b.classList.add('correct');else if(ai===a)b.classList.add('wrong')});$(`feedback${i}`).textContent=(a===q.answer?'正解。':'不正解。')+q.why})}
function init(){document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;document.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('active',x===b));renderList()});document.querySelectorAll('[data-purpose]').forEach(b=>b.onclick=()=>{purpose=b.dataset.purpose;renderPurpose();renderList()});$('search').oninput=renderList;$('clearSearch').onclick=()=>{$('search').value='';renderList()};renderQuiz();renderList();const q=new URLSearchParams(location.search),id=q.get('lesson');if(id&&lessons.some(x=>x.id===id))showDetail(id);else showDetail('pivot')}
init();
})();