(()=>{
'use strict';
const KEY='neet-note-releases-v1', SONGS='song-note-songs-v1';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{const raw=localStorage.getItem(k);const v=raw===null?[]:JSON.parse(raw);if(!Array.isArray(v))throw new Error('保存データの形式を確認できません');return v};
let mode=new URLSearchParams(location.search).get('mode')==='live'?'live':'album', selected=null, rows=[], dirty=false,blocked=false;
try{rows=read(KEY)}catch(e){blocked=true;$('#save-state').textContent='保存データを読めないため編集を停止しました。再読み込みしてください。'}
const current=()=>rows.find(r=>r.id===selected&&!r.deletedAt);
const stamp=()=>new Date().toISOString();
function persist(){if(blocked)return false;try{localStorage.setItem(KEY,JSON.stringify(rows));dirty=false;$('#save-state').textContent='この端末に保存済み';return true}catch(e){dirty=true;$('#save-state').textContent='保存できませんでした。画面を閉じずに、画像を小さくするか端末の空き容量を確認してください。';return false}}
function update(){const r=current();if(r)r.updatedAt=stamp();dirty=true;persist()}
function field(label,key,value,type='text'){return `<label>${label}<input data-field="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="1"':''}></label>`}
function area(label,key,value){return `<label class="wide">${label}<textarea data-field="${key}">${esc(value)}</textarea></label>`}
function coverSafe(v){return /^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v||'')}
function list(){const visible=rows.filter(r=>r.kind===mode&&!r.deletedAt);$('#projects').innerHTML=visible.map(r=>`<button type="button" class="project" data-open="${esc(r.id)}" aria-current="${r.id===selected}">${coverSafe(r.cover)?`<img class="thumb" src="${r.cover}" alt="">`:''}<span><b>${esc(r.title|| (mode==='live'?'タイトル未設定のライブ':'タイトル未設定の作品'))}</b><small>${esc(r.date?.replace('T',' ')||'日程未定')} · ${r.tracks.length}曲</small></span></button>`).join('')||'<p>まだ登録されていません。</p>'}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('h1').textContent=mode==='live'?'ライブモード':'マイアルバム';$('#new-project').textContent=mode==='live'?'＋ ライブを作成':'＋ アルバム・シングルを作成';$('#new-project').disabled=blocked;list();const r=current();if(!r){$('#editor').innerHTML=`<div class="panel empty"><h2>${mode==='live'?'次のライブを組もう':'次のリリースを組もう'}</h2><p>「＋ ${mode==='live'?'ライブ':'アルバム・シングル'}を作成」から始められます。</p></div>`;return}
const live=r.kind==='live';let songs=[];try{songs=read(SONGS).filter(s=>!s.deletedAt)}catch{}
$('#editor').innerHTML=`<section class="panel"><h2>${live?'ライブ情報':'リリース情報'}</h2>${live?'':`<div class="cover-area">${coverSafe(r.cover)?`<img class="cover" src="${r.cover}" alt="ジャケット写真">`:'<div class="cover cover-empty">ジャケット</div>'}<div class="cover-controls"><label>ジャケット写真<input id="cover-file" type="file" accept="image/jpeg,image/png,image/webp"></label><small>画像は保存用に縮小されます。</small>${r.cover?'<button type="button" data-action="remove-cover">写真を外す</button>':''}</div></div>`}<div class="fields">${field(live?'ライブ名':'タイトル','title',r.title)}${field(live?'開催日時':'発売日','date',r.date,live?'datetime-local':'date')}${live?field('会場','venue',r.venue)+field('キャパ（人）','capacity',r.capacity,'number'):`<label>発表形態<select data-field="format">${['アルバム','シングル','EP','ミニアルバム'].map(v=>`<option ${r.format===v?'selected':''}>${v}</option>`).join('')}</select></label>${field('リリース方法（配信・CDなど）','medium',r.medium)}`}${area(live?'ライブ全体のメモ':'作品の説明','description',r.description)}</div></section><section class="panel"><h2>${live?'セットリスト':'収録曲'} <span id="track-count">${r.tracks.length}曲</span></h2><div id="tracks">${r.tracks.map((t,i)=>`<article class="track" data-track="${esc(t.id)}"><div class="track-head"><span class="number">${String(i+1).padStart(2,'0')}</span><div class="track-actions"><button type="button" data-action="up" aria-label="${i+1}曲目を上へ" ${i===0?'disabled':''}>↑</button><button type="button" data-action="down" aria-label="${i+1}曲目を下へ" ${i===r.tracks.length-1?'disabled':''}>↓</button><button type="button" data-action="remove-track">外す</button></div></div><div class="fields">${field('曲名','title',t.title)}${live?field('キー','key',t.key)+field('BPM','bpm',t.bpm,'number')+area('アレンジ・演奏メモ','arrangement',t.arrangement):''}${area('曲の説明','description',t.description)}</div>${t.songId&&songs.some(s=>s.id===t.songId)?`<a class="note-link" href="index.html?mode=note&song=${encodeURIComponent(t.songId)}">元の曲ノートを開く</a>`:''}</article>`).join('')||'<p>曲を追加して、曲順を組んでみましょう。</p>'}</div><div class="add-track"><label>作成した曲から選ぶ<select id="song-picker"><option value="">曲を選択</option>${songs.map(s=>`<option value="${esc(s.id)}">${esc(s.title||'無題の曲')}</option>`).join('')}</select></label><button type="button" data-action="add-song">追加</button><button type="button" data-action="add-blank">曲名を手入力</button></div></section><div class="footer-actions"><span>入力内容は自動保存されます</span><button type="button" class="danger" data-action="delete-project">${live?'ライブ':'作品'}を削除</button></div>`;
}
$('#new-project').onclick=()=>{if(blocked)return;const r={id:crypto.randomUUID(),kind:mode,title:'',date:'',format:'アルバム',medium:'',venue:'',capacity:'',description:'',cover:'',tracks:[],createdAt:stamp(),updatedAt:stamp()};rows.unshift(r);selected=r.id;persist();render();$('#editor input[data-field=title]')?.focus()};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(dirty&&!persist())return;mode=b.dataset.mode;selected=null;history.replaceState(null,'',`?mode=${mode}`);render()});
$('#projects').onclick=e=>{const b=e.target.closest('[data-open]');if(!b)return;if(dirty&&!persist())return;selected=b.dataset.open;render()};
$('#editor').addEventListener('input',e=>{const f=e.target.dataset.field,r=current();if(!f||!r)return;if(e.target.type==='number'&&!e.target.validity.valid){$('#save-state').textContent='人数・BPMには0以上の整数を入力してください。';return}const article=e.target.closest('[data-track]');const target=article?r.tracks.find(t=>t.id===article.dataset.track):r;target[f]=e.target.value;update();if(!article&&(f==='title'||f==='date'))list()});
$('#editor').addEventListener('click',e=>{const b=e.target.closest('[data-action]'),r=current();if(!b||!r)return;const action=b.dataset.action,article=b.closest('[data-track]'),i=article?r.tracks.findIndex(t=>t.id===article.dataset.track):-1;
if(action==='delete-project'){if(!confirm('この'+(mode==='live'?'ライブ':'作品')+'を削除しますか？ 元の曲ノートは残ります。'))return;r.deletedAt=stamp();update();selected=null}
if(action==='remove-cover'){r.cover='';update()}
if(action==='up'&&i>0){[r.tracks[i-1],r.tracks[i]]=[r.tracks[i],r.tracks[i-1]];update()}
if(action==='down'&&i>=0&&i<r.tracks.length-1){[r.tracks[i+1],r.tracks[i]]=[r.tracks[i],r.tracks[i+1]];update()}
if(action==='remove-track'&&i>=0){if(!confirm('この曲をリストから外しますか？ 曲ごとの説明・アレンジも外れます。'))return;r.tracks.splice(i,1);update()}
if(action==='add-song'||action==='add-blank'){let s={};if(action==='add-song'){try{s=read(SONGS).find(s=>s.id===$('#song-picker').value&&!s.deletedAt)}catch{}if(!s?.id){$('#save-state').textContent='追加する曲を選択してください。';return}}r.tracks.push({id:crypto.randomUUID(),songId:s.id||'',title:s.title||'',key:s.key||'',bpm:s.bpm||'',description:'',arrangement:''});update()}
render();if(action==='add-blank')$('#tracks .track:last-child input')?.focus();
});
$('#editor').addEventListener('change',async e=>{if(e.target.id!=='cover-file')return;const file=e.target.files?.[0],r=current();if(!file||!r)return;const targetId=r.id;try{if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('JPEG・PNG・WebPの写真を選んでください。');if(file.size>20*1024*1024)throw new Error('20MB以下の写真を選んでください。');const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('写真を読み込めませんでした。'));img.src=url});const canvas=document.createElement('canvas'),scale=Math.min(1,480/Math.max(img.width,img.height));canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',.7);if(data.length>65000)data=canvas.toDataURL('image/jpeg',.4);if(data.length>90000)throw new Error('写真のサイズが大きすぎます。小さい写真を選んでください。');if(r.deletedAt)return;r.cover=data;r.updatedAt=stamp();persist();if(selected===targetId)render()}finally{URL.revokeObjectURL(url)}}catch(error){$('#save-state').textContent=error.message}});
window.addEventListener('storage',e=>{if(e.key!==KEY)return;if(dirty){$('#save-state').textContent='別タブで変更があります。未保存の内容を確認してください。';return}try{rows=read(KEY);render()}catch{}});
window.addEventListener('neet-note:before-sync',()=>{if(dirty)persist()});
window.addEventListener('neet-note:sync-status',e=>{$('#sync-state').textContent=e.detail.text});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
render();
})();
