(()=>{
'use strict';
const TOPICS=[
{id:'interval',cat:'基礎',title:'音程',keywords:'音程 度数 半音 全音 長3度 短3度 完全5度',short:'2つの音の距離。コードとスケールの一番小さい材料。',simple:'「基準の音からどれくらい離れているか」を数字と種類で表したもの。',body:'音程は度数と半音数の両方で考える。1・4・5・8度は完全系、2・3・6・7度は長短系として扱うのが基本。コードの明るさ・暗さ・緊張感は、構成音同士の音程関係から生まれる。',example:'C→Eは長3度、C→E♭は短3度、C→Gは完全5度。',use:'コード名を丸暗記するより、ルートから3度・5度・7度がどう変化しているかを見ると、初めて見るコードも理解しやすい。'},
{id:'degree',cat:'基礎',title:'度数とローマ数字',keywords:'度数 ローマ数字 I ii iii IV V vi vii ディグリー',short:'音やコードを「キーの何番目か」で読む共通言語。',simple:'CやGという名前ではなく、1番目・5番目のように役割で見る方法。',body:'ルートを1度として各音を数え、コード進行ではI・ii・Vなどのローマ数字で表す。大文字はメジャー、小文字はマイナーを表すことが多い。キーが変わっても進行の形を同じまま比較できる。',example:'C–G–Am–F = I–V–vi–IV。Gキーなら G–D–Em–C。',use:'移調・作曲・進行分析ではローマ数字で覚えると、12キーすべてにそのまま応用できる。'},
{id:'key',cat:'基礎',title:'キー・音階・調号・五度圏',keywords:'キー 音階 調号 五度圏 平行調 同主調',short:'曲の中心音と、そこで使われやすい音の集合。',simple:'曲が最終的に帰ってきたくなる場所と、その周りの仲間の音。',body:'メジャースケールは全・全・半・全・全・全・半。ナチュラルマイナーは全・半・全・全・半・全・全。五度圏では完全5度ずつ移動すると調号の関係を整理でき、近いキーほど共通音が多い。平行調は使う音が同じ長短調、同主調は主音が同じ長短調。',example:'CメジャーとAマイナーは平行調。CメジャーとCマイナーは同主調。',use:'転調先・借用和音・近いキーを探す時の地図として使える。'},
{id:'triad',cat:'コード構成',title:'三和音と7thコード',keywords:'三和音 トライアド メジャー マイナー dim aug 7th maj7 m7',short:'1・3・5を基本に、7度を加えるとコードの性格がより明確になる。',simple:'3番目と5番目、さらに7番目の音を変えるとコードの表情が変わる。',body:'メジャーは1・3・5、マイナーは1・♭3・5、dimは1・♭3・♭5、augは1・3・♯5。7thコードではさらに7度を重ね、maj7・7・m7・m7♭5などに分かれる。3度と7度はコードの性格を特に強く決める。',example:'Cmaj7=C E G B / C7=C E G B♭ / Cm7=C E♭ G B♭。',use:'メロディ音が3rdや7thに入るとコード感が強く出るので、理論アシストの候補判断にも重要。'},
{id:'susadd',cat:'コード構成',title:'sus・add・omit',keywords:'sus sus2 sus4 add9 omit no3 no5',short:'susは置換、addは追加、omitは省略。',simple:'音を入れ替える・足す・抜くの違い。',body:'sus2/sus4はコードの3度を2度または4度へ置き換える。add9は三和音を残したまま9度を追加する。omitやnoは指定音を省略する。susでは3度が消えるため、メジャー・マイナー感が一時的に曖昧になる。',example:'C=C E G / Csus4=C F G / Cadd9=C E G D / C(no3)=C G。',use:'サビ前でsus4を使って解決を待たせたり、add9で透明感を足したりできる。'},
{id:'slash',cat:'コード構成',title:'オンコード・転回形',keywords:'オンコード スラッシュコード 転回形 inversion ベース',short:'同じコードでも最低音を変えると、進行の流れが大きく変わる。',simple:'コードはそのまま、いちばん低い音だけ変える考え方。',body:'C/Eのように右側の音をベースへ置く。構成音を最低音にしたものは転回形として整理できる。コード機能を大きく変えず、ベースラインを順次進行させたり、響きの重心を変えたりできる。',example:'C→G/B→Am ならベースが C→B→A と滑らかに下降する。',use:'コード候補を決めたあと「ベースだけ滑らかにしたい」時にオンコードを検討すると自然。'},
{id:'guide',cat:'コード構成',title:'ガイドトーンとシェルボイシング',keywords:'ガイドトーン 3度 7度 シェルボイシング shell voicing',short:'少ない音数でコードの性格を伝えるための中心音。',simple:'コードらしさを決める3度と7度を優先する方法。',body:'3度はメジャー/マイナーを、7度はmaj7/7などの違いを決める。ジャズではルート・3度・7度を中心にしたシェルボイシングがよく使われ、5度は省略されることも多い。',example:'G7のガイドトーンはBとF。B→C、F→Eと動くとCmaj7へ強く解決する。',use:'バンドで音が濁る時やテンションを足したい時、まず3rdと7thを残して他を整理すると使いやすい。'},
{id:'voicing',cat:'コード構成',title:'ボイシング・Drop2・Drop3',keywords:'ボイシング クローズ オープン drop2 drop3 ドロップ2',short:'同じ構成音でも並べ方で密度・広がり・弾きやすさが変わる。',simple:'同じコードの音を、近く集めるか広く散らすか。',body:'クローズボイシングは構成音を狭い音域にまとめ、オープンボイシングは音の間隔を広げる。Drop2/Drop3は上から2番目・3番目の音を1オクターブ下げ、4声コードをギターやアンサンブルで扱いやすくする。',example:'Cmaj7の4声配置を並べ替えても構成音が同じならコード名は保たれる。',use:'同じ進行を繰り返す時、コード自体を変えずにボイシングを変えるだけでも展開を作れる。'},
{id:'upper',cat:'コード構成',title:'アッパーストラクチャー',keywords:'アッパーストラクチャー upper structure triad テンション',short:'土台のコード上に別の三和音を重ね、テンションを整理する。',simple:'難しいテンションを「上に別の小さなコードが乗っている」と考える。',body:'ドミナントなどの上に別の三和音を置き、9th・♯11・13などをまとめて作る考え方。複雑なテンションを音の塊として把握できる反面、メロディや低音との衝突は確認が必要。',example:'C7の上にDメジャートライアドを置くと D・F♯・A が9・♯11・13として働く。',use:'ピアノ・ギターの分数的なボイシングや、ジャズ/フュージョン系の色を作る時に便利。'},
{id:'function',cat:'進行理論',title:'機能和声 T / SD / D',keywords:'機能和声 トニック サブドミナント ドミナント T SD D',short:'コードを安定・展開・緊張の役割で読む。',simple:'落ち着く→広がる→戻りたくなる、の3役。',body:'トニックは安定、サブドミナントは中心から外へ広がる感じ、ドミナントはトニックへ戻りたがる緊張を作る。すべてのコードが必ず1つに固定されるわけではないが、進行の方向を読む大きな手掛かりになる。',example:'Cキーなら C(I)=T、F(IV)=SD、G(V)=D。C→F→G→C は T→SD→D→T。',use:'次コードに迷った時は「今は安定・展開・緊張のどこ？」と考えると候補を絞りやすい。'},
{id:'cadence',cat:'進行理論',title:'終止（カデンツ）',keywords:'終止 カデンツ 正格 変格 半終止 偽終止',short:'フレーズに句読点を作る着地パターン。',simple:'曲をどう一区切りさせるかの型。',body:'V→Iは強い正格終止、IV→Iは柔らかい変格終止、V→viは着地を外す偽終止、Vで止まる半終止は続きを強く期待させる。V7→Iでは導音と7thの解決が終止感を強める。',example:'G7→C / F→C / G7→Am / Dm→G。',use:'Aメロ末、サビ前、サビ終わりで終止の強さを変えるとセクション差が出る。'},
{id:'dominant',cat:'進行理論',title:'ドミナントモーション',keywords:'ドミナントモーション 5度進行 V I ツーファイブ',short:'ルートが完全5度下へ進む、強い解決方向。',simple:'次のコードへ強く引っぱる王道の動き。',body:'V→Iが代表で、3rdと7thを含むドミナント7thでは半音解決が生まれるため引力が強い。5度進行を連続すると循環的な進行も作れる。',example:'G7→C、E7→Am、A7→Dm。',use:'進行に「行き先」を作りたい時、目的コードの5度上に7thコードを置く発想が基本。'},
{id:'secondary',cat:'進行理論',title:'セカンダリードミナント',keywords:'セカンダリードミナント V/ii V/V V/vi secondary dominant',short:'ダイアトニック内のコードを一時的な主役にして、そのV7を置く。',simple:'次のコードを一瞬だけ「仮のトニック」にする。',body:'本来のキー外の音を使い、目的コードへの引力を強める。V/ii、V/Vのように「どの度数へ向かうVか」で表す。転調と違い、短時間だけ目的コードを強調して元キーへ戻ることも多い。',example:'Cキーで A7→Dm = V/ii→ii、D7→G = V/V→V、E7→Am = V/vi→vi。',use:'ダイアトニックだけでは平坦な時、目的コードの5度上を7thにすると推進力を足せる。'},
{id:'modal',cat:'進行理論',title:'モーダルインターチェンジ（借用和音）',keywords:'借用和音 モーダルインターチェンジ iv bVI bVII 同主調',short:'同じ主音を持つ別の調・モードからコードを借りる。',simple:'Cメジャーの中へCマイナー側の色を一瞬入れるような考え方。',body:'キー中心は保ったまま、同主調や平行するモードからコードを借りる。メジャーキーではiv、♭VI、♭VIIなどが代表的。機能を完全に変えず、感情や景色だけを一瞬変えやすい。',example:'Cメジャーで Fm(iv)→C、A♭(♭VI)、B♭(♭VII)。',use:'切なさ・映画的な色・サビ前の意外性などを作る時に強い。'},
{id:'substitute',cat:'進行理論',title:'サブスティテュートドミナント（subV）',keywords:'subV 裏コード サブスティテュート トライトーン',short:'V7を、同じトライトーンを持つ別の7thへ置き換える。',simple:'行き先は同じまま、ベースラインだけ半音で近づけられる代理ドミナント。',body:'ドミナント7thの3rdと7thが作るトライトーンを共有する、ルートが増4度離れた7thコードで置換する。解決方向を保ちつつクロマチックなベースを作れる。',example:'G7→C の代わりに D♭7→C。Dm7–D♭7–Cmaj7 とすれば D→D♭→C。',use:'II–V–Iを少しジャズ寄りにしたい時や、半音下降ラインを作りたい時に使いやすい。'},
{id:'diminished',cat:'進行理論',title:'ディミニッシュと経過和音',keywords:'dim dim7 ディミニッシュ 経過和音 passing chord',short:'対称構造を使って、コード同士を半音でつなぐ。',simple:'目的地へ行く途中に置く、強い「橋」のコード。',body:'dim7は短3度を積み重ねた対称的な構造で、転回しても同じ4音集合になる。複数の導音和音として読み替えられ、目的コードの半音下から接近したり、ドミナント7(♭9)のルート省略形として扱ったりできる。',example:'C→C♯dim7→Dm。Bdim7=B D F A♭はDdim7等と同じ音集合。',use:'ベースを半音でつなぎたい時や、短い経過コードで緊張を足したい時に便利。'},
{id:'voiceleading',cat:'進行理論',title:'ボイスリーディング（声部進行）',keywords:'ボイスリーディング 声部進行 共通音 半音進行 内声',short:'各構成音をできるだけ小さく動かしてコードをつなぐ。',simple:'コード全体ではなく、1本1本の音の線を見る考え方。',body:'共通音は保ち、他の音は半音・全音など最短距離で次のコードトーンへ動かすと、進行が滑らかに聞こえる。ガイドトーンの3rd・7thの解決は特に重要。',example:'G7(B F)→Cmaj7(C E) では B→C、F→E と半音で解決。',use:'候補コードが複数ある時、共通音が多く各声部の移動が小さい方を選ぶと自然なつながりを作りやすい。'},
{id:'pedal',cat:'進行理論',title:'ペダルポイント',keywords:'ペダルポイント pedal 持続音 common tone',short:'1音を保ったまま上のコードを変える。',simple:'同じ低音や高音を鳴らし続けながら、周りだけ変える。',body:'トニック・ドミナントなどの音を長く保ち、その上で和音を動かすことで統一感と緊張を同時に作る。機能和声だけでは説明しづらい浮遊感や映画的な持続感を作れる。',example:'ベースCを保ちながら C→F/C→G/C→C。',use:'イントロ、間奏、ビルドアップ、映像的な場面で「同じ場所にいるのに景色だけ変わる」感じを作れる。'},
{id:'minor',cat:'スケール・旋律',title:'短調の3種類',keywords:'ナチュラルマイナー ハーモニックマイナー メロディックマイナー',short:'短調は3種類を使い分けて、導音・旋律・テンションを作る。',simple:'マイナーの6番目・7番目を必要に応じて変える。',body:'ナチュラルマイナーが基本形。ハーモニックマイナーは第7音を上げてV7→iを強化する。ジャズのメロディックマイナーは第6・7音を上げた形を上下行とも用い、派生モードも重要になる。',example:'A natural=A B C D E F G / harmonic=G♯ / melodic=F♯ G♯。',use:'マイナー曲でE7→Amを強くしたいならG♯、mMaj7やaltered系ではメロディックマイナーの発想が役立つ。'},
{id:'modes',cat:'スケール・旋律',title:'教会旋法7種類（モード）',keywords:'モード イオニアン ドリアン フリジアン リディアン ミクソリディアン エオリアン ロクリアン',short:'同じ音材料でも中心音と特徴音を変えると、別の色になる。',simple:'同じ7音でも「どの音を家にするか」で雰囲気が変わる。',body:'Ionian、Dorian、Phrygian、Lydian、Mixolydian、Aeolian、Locrianの7種類。モードは対応コードだけでなく特徴音を意識すると聞き分けやすい。機能和声の強いV→Iを使いすぎるとモード感が薄くなることもある。',example:'D Dorian=D E F G A B C。F Lydian=F G A B C D E。G Mixolydian=G A B C D E F。',use:'1つのコードを長く保つ曲、ファンク、ロック、映画音楽などで特徴音をメロディに置くと色が出る。'},
{id:'altered',cat:'スケール・旋律',title:'オルタードスケール',keywords:'altered オルタード b9 #9 b5 #5 ドミナント',short:'V7を強く不安定にして解決を濃くするドミナント用スケール。',simple:'ドミナントに強い緊張音を集めた音階。',body:'♭9・♯9・♭5(♯11)・♯5(♭13)などを含む。3rdと♭7を軸にしながら、各テンションを半音で解決させると機能が明確になる。メロディックマイナー第7モードとして整理される。',example:'G7alt：G A♭ B♭ B D♭ E♭ F → Cへ解決。',use:'ジャズ寄りのV7→Iで、解決直前だけ緊張を最大化したい時に使う。'},
{id:'nonchord',cat:'スケール・旋律',title:'非和声音',keywords:'非和声音 経過音 刺繍音 掛留音 先取音',short:'コード外音も「どこから来てどこへ解決するか」で自然に使える。',simple:'コードに入っていない音でも、短く通過したり解決すればメロディになる。',body:'経過音・刺繍音・掛留音・先取音などは、コードトーン間をつないだり一時的な緊張を作ったりする。強拍や長い音ほどコードトーンとの関係が目立つため、解決先を設計することが重要。',example:'Cコード上で E→F→G と動く時、Fを経過音として扱う。',use:'メロディ音が候補コードに含まれなくても、即NGにせず「短い非和声音か」「次にどこへ解決するか」を見る。'},
{id:'chordscale',cat:'スケール・旋律',title:'コードスケール',keywords:'コードスケール Ionian Dorian Mixolydian tension avoid',short:'そのコード上で使える音を、コードトーン・テンション・注意音に分けて考える。',simple:'コードごとに「安定する音・色を足す音・扱い注意の音」を整理する。',body:'ダイアトニックコードには各度数に対応するモードを当てる考え方が基本。コードトーンを核に、テンションとコードトーンの半音衝突や機能を確認する。ドミナントでは目的に応じてMixolydian、alteredなど候補が変わる。',example:'Cmaj7→C Ionian、Dm7→D Dorian、G7→G Mixolydian。',use:'理論アシストの「使えるスケール」は、コードトーン→テンション→注意音の順に見ると実践的。'},
{id:'modulation',cat:'作曲・編曲',title:'転調',keywords:'転調 modulation ピボット 共通コード 直接転調',short:'曲の中心となるキーそのものを別のキーへ移す。',simple:'曲の「帰る場所」を途中で別の音に変える。',body:'共通コードを使うピボット転調、新キーのドミナントを使う転調、直接転調などがある。セカンダリードミナントとの違いは、新しいキーが数小節以上中心として感じられるかどうか。',example:'CキーのAmをGキーのiiとして読み替え、Am→D7→G。',use:'Bメロやラスサビで景色を変える時、「共通コード→新キーのV→新I」を探すと自然に設計しやすい。'},
{id:'reharm',cat:'作曲・編曲',title:'リハーモナイズ',keywords:'リハーモナイズ 代理コード 借用 メロディ セカンダリー',short:'メロディを保ちながら、コードだけを別の解釈へ付け替える。',simple:'歌メロは同じまま伴奏コードを作り直す。',body:'まずメロディの強拍・長い音を確認し、それを含むコードを候補化する。次に機能の近い代理、借用和音、セカンダリードミナント、subV、経過和音、転回形などを使って差し替える。変更後はベースと声部進行も確認する。',example:'C–Am–F–G → Cmaj7–A7–Dm7–G7 のように色と推進力を追加。',use:'理論アシストの候補を「正解探し」ではなく、メロディを保った複数の和声解釈として使える。'},
{id:'bassline',cat:'作曲・編曲',title:'ベースライン設計',keywords:'ベースライン オンコード 順次進行 反行',short:'ルートだけでなく転回形や経過音を使って低音を旋律としてつなぐ。',simple:'コードの一番下の音も、もう1本のメロディとして考える。',body:'1拍目は和声の土台を明確にしつつ、コード間では半音・全音の順次進行を優先すると滑らかになる。オンコード、経過音、反行を使うと同じコード進行でも動きが生まれる。',example:'C→G/B→Am→C/G→F で C→B→A→G→F の下降ライン。',use:'候補コードを選んだあと、最低音だけ見直すと「プロっぽいつながり」に変えやすい。'},
{id:'motif',cat:'作曲・編曲',title:'モチーフ展開とフック',keywords:'モチーフ フック 反復 反行 リズム 変奏',short:'短い音型を反復し、小さく変化させて曲全体の統一感を作る。',simple:'覚えやすい短いフレーズを、少しずつ変えて何度も使う。',body:'移高・反行・リズム変更・拡大縮小などでモチーフを展開する。完全な反復だけでは停滞しやすく、毎回すべて変えると統一感が消えるため「同じ部分＋変わる部分」の両方を残す。',example:'C–D–Eの3音モチーフを D–E–F に移高、またはリズムだけ変えてサビで再利用。',use:'コード理論だけで曲を作るのではなく、メロディ側にも共通モチーフを置くとセクション同士がつながる。'}
];
const byId=id=>TOPICS.find(x=>x.id===id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function compactCard(id){const x=byId(id);if(!x)return'';return `<article class="neet-explain"><div class="neet-explain-head"><span>📖</span><div><b>${esc(x.title)}</b><small>${esc(x.short)}</small></div></div><div class="neet-explain-body"><p>${esc(x.body)}</p><div><strong>例</strong>${esc(x.example)}</div><div><strong>作曲でどう使う？</strong>${esc(x.use)}</div></div></article>`}
function libraryCard(x){return `<details class="neet-theory-item" data-cat="${esc(x.cat)}" data-search="${esc((x.title+' '+x.keywords+' '+x.short+' '+x.body).toLowerCase())}"><summary><span class="neet-theory-cat">${esc(x.cat)}</span><b>${esc(x.title)}</b><small>${esc(x.short)}</small></summary><div class="neet-theory-detail"><div><strong>超ざっくり</strong><p>${esc(x.simple)}</p></div><div><strong>仕組み</strong><p>${esc(x.body)}</p></div><div><strong>例</strong><p>${esc(x.example)}</p></div><div class="use"><strong>作曲・分析で使う</strong><p>${esc(x.use)}</p></div></div></details>`}
function installStyles(){if(document.getElementById('neet-theory-guide-style'))return;const s=document.createElement('style');s.id='neet-theory-guide-style';s.textContent=`
.neet-explain{margin:10px 0 0;padding:12px;border:1px solid var(--line,#ded6c9);border-radius:14px;background:#fff}.neet-explain-head{display:flex;gap:9px;align-items:flex-start}.neet-explain-head>span{display:grid;place-items:center;width:32px;height:32px;flex:0 0 32px;border-radius:10px;background:var(--soft,#f4eee4)}.neet-explain-head b{display:block;font-size:.9rem}.neet-explain-head small{display:block;margin-top:2px;color:var(--muted,#71695f);font-size:.73rem;line-height:1.45}.neet-explain-body{margin-top:9px;font-size:.78rem;line-height:1.68;color:var(--ink,#1f2937)}.neet-explain-body p{margin:0 0 8px}.neet-explain-body>div{margin-top:7px;padding:8px 9px;border-radius:10px;background:var(--soft,#f4eee4)}.neet-explain-body strong{display:block;margin-bottom:3px;color:var(--accent,#8b6f47);font-size:.68rem;letter-spacing:.06em}
.neet-guide-top{margin:0 0 13px;padding:13px;border:1px solid #d8c9b5;border-radius:14px;background:#fff9ef}.neet-guide-top b{display:block;margin-bottom:4px}.neet-guide-top p{margin:0;color:#685a48;font-size:.78rem;line-height:1.6}.neet-guide-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:9px}.neet-guide-grid a{padding:8px 9px;border:1px solid #e3d8c9;border-radius:10px;background:#fff;color:inherit;text-decoration:none;font-size:.75rem;font-weight:850}
.neet-unified-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.neet-unified-head p{margin:4px 0 0;color:var(--muted,#71695f);font-size:.78rem;line-height:1.55}.neet-source-badge{flex:0 0 auto;padding:5px 8px;border-radius:999px;background:#e8dfd1;color:#6c5537;font-size:.66rem;font-weight:900}.neet-theory-controls{display:grid;grid-template-columns:1fr auto;gap:8px;margin:12px 0 9px}.neet-theory-controls input{width:100%;padding:10px 11px;border:1px solid var(--line,#ded6c9);border-radius:11px;background:#fff;color:inherit}.neet-theory-count{align-self:center;color:var(--muted,#71695f);font-size:.72rem;font-weight:850}.neet-cat-tabs{display:flex;gap:6px;overflow-x:auto;padding:2px 0 10px;scrollbar-width:none}.neet-cat-tabs::-webkit-scrollbar{display:none}.neet-cat-tabs button{flex:0 0 auto;padding:7px 10px;border:1px solid var(--line,#ded6c9);border-radius:999px;background:#fff;color:var(--muted,#71695f);font-size:.73rem}.neet-cat-tabs button.active{background:var(--accent,#8b6f47);color:#fff;border-color:var(--accent,#8b6f47)}.neet-theory-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.neet-theory-item{border:1px solid var(--line,#ded6c9);border-radius:14px;background:#fff;overflow:hidden}.neet-theory-item[open]{box-shadow:0 7px 20px rgba(80,60,30,.06)}.neet-theory-item summary{display:grid;grid-template-columns:auto 1fr;gap:4px 8px;align-items:center;padding:12px;cursor:pointer;list-style:none}.neet-theory-item summary::-webkit-details-marker{display:none}.neet-theory-item summary b{font-size:.9rem}.neet-theory-item summary small{grid-column:1/-1;color:var(--muted,#71695f);font-size:.72rem;line-height:1.45}.neet-theory-cat{display:inline-flex;width:max-content;padding:3px 6px;border-radius:999px;background:var(--soft,#f4eee4);color:#6d5940;font-size:.61rem;font-weight:900}.neet-theory-detail{display:grid;gap:7px;padding:0 12px 12px}.neet-theory-detail>div{padding:9px;border-radius:10px;background:var(--soft,#f4eee4)}.neet-theory-detail>div.use{background:#eef6f1}.neet-theory-detail strong{display:block;margin-bottom:3px;color:var(--accent,#8b6f47);font-size:.68rem}.neet-theory-detail p{margin:0;font-size:.76rem;line-height:1.62}.neet-theory-empty{grid-column:1/-1;padding:20px;text-align:center;color:var(--muted,#71695f)}.neet-original-link{display:inline-flex;margin-top:10px;color:var(--accent,#8b6f47);font-size:.74rem;font-weight:900;text-decoration:none}
@media(max-width:700px){.neet-guide-grid,.neet-theory-list{grid-template-columns:1fr}.neet-theory-controls{grid-template-columns:1fr}.neet-theory-count{justify-self:start}.neet-unified-head{display:block}.neet-source-badge{display:inline-flex;margin-top:8px}}
`;document.head.appendChild(s)}
function addTopGuide(){const lead=document.querySelector('.source-note')||document.querySelector('.lead');if(!lead||document.querySelector('.neet-guide-top'))return;const box=document.createElement('section');box.className='neet-guide-top';box.innerHTML=`<b>理論アシスト × コード辞典を統合したよ</b><p>分析ツールだけじゃなく、コード辞典側の「コードの作り方・ボイシング・モード・作曲理論」も同じページで読めるように統合。まず ①構成音 → ②機能 → ③声部の動き → ④色彩・スケール の順で見ると、候補コードの理由まで理解しやすい。</p><div class="neet-guide-grid"><a href="#neetUnifiedTheory">📚 統合理論ライブラリへ</a><a href="#neetUnifiedTheory">🎸 コード構成・ボイシング</a><a href="#neetUnifiedTheory">🧭 機能・進行・代理</a><a href="#neetUnifiedTheory">✨ スケール・作曲応用</a></div>`;lead.insertAdjacentElement('afterend',box)}
function enrichTopics(){const map=[['音程','interval'],['度数','degree'],['音階','key'],['調号','key'],['五度圏','key'],['三和音','triad'],['七の和音','triad'],['機能','function'],['終止','cadence'],['短調','minor'],['テンション','chordscale'],['セカンダリー','secondary'],['モーダル','modal'],['借用','modal'],['サブスティテュート','substitute'],['subV','substitute'],['ディミニッシュ','diminished'],['転調','modulation'],['コードスケール','chordscale'],['ペダル','pedal'],['オンコード','slash'],['転回','slash'],['ボイシング','voicing']];[...document.querySelectorAll('.topic')].forEach(t=>{const text=t.textContent||'';const hit=map.find(([n])=>text.includes(n));if(hit&&!t.querySelector('.neet-explain'))t.insertAdjacentHTML('beforeend',compactCard(hit[1]))})}
function enrichHeadings(){const all=[...document.querySelectorAll('h2,h3')];[['使えるスケール','chordscale'],['メロディ音の役割','nonchord'],['色を変えるコード','modal'],['キー','key'],['ダイアトニック','triad'],['進行','function']].forEach(([word,id])=>{const h=all.find(x=>(x.textContent||'').includes(word));const host=h?.parentElement;if(host&&!host.querySelector('.neet-explain'))host.insertAdjacentHTML('beforeend',compactCard(id))})}
function makeUnifiedLibrary(){if(document.getElementById('neetUnifiedTheory'))return;const old=document.getElementById('neetQuickGlossary');if(old)old.remove();const root=document.querySelector('.wrap')||document.body;const sec=document.createElement('section');sec.className='card wide';sec.id='neetUnifiedTheory';sec.style.marginTop='13px';const cats=['すべて',...new Set(TOPICS.map(x=>x.cat))];sec.innerHTML=`<div class="neet-unified-head"><div><h2>📚 統合理論ライブラリ</h2><p>NEETNOTEの分析用理論と、コード辞典の基礎・コード構成・ボイシング・モード・作曲理論を1つにまとめたよ。項目を開くと「超ざっくり → 仕組み → 例 → 作曲で使う」の順で読める。</p></div><span class="neet-source-badge">THEORY ASSIST × CHORD BOOK</span></div><div class="neet-theory-controls"><input id="neetTheorySearch" type="search" placeholder="例：裏コード、転回形、ドリアン、リハーモナイズ"><span id="neetTheoryCount" class="neet-theory-count"></span></div><div class="neet-cat-tabs">${cats.map((c,i)=>`<button type="button" data-neet-cat="${esc(c)}" class="${i===0?'active':''}">${esc(c)}</button>`).join('')}</div><div id="neetTheoryList" class="neet-theory-list">${TOPICS.map(libraryCard).join('')}</div><a class="neet-original-link" href="https://akito0802.github.io/Cordhyo-/theory.html" target="_blank" rel="noopener">コード辞典側の理論ページも開く ↗</a>`;root.appendChild(sec);let active='すべて';const input=sec.querySelector('#neetTheorySearch'),count=sec.querySelector('#neetTheoryCount'),list=sec.querySelector('#neetTheoryList');function render(){const q=input.value.trim().toLowerCase();let shown=0;[...list.querySelectorAll('.neet-theory-item')].forEach(el=>{const cat=el.dataset.cat||'',text=el.dataset.search||'';const okCat=active==='すべて'||cat===active;const okQ=!q||text.includes(q);el.hidden=!(okCat&&okQ);if(!el.hidden)shown++});let empty=list.querySelector('.neet-theory-empty');if(!shown){if(!empty){empty=document.createElement('div');empty.className='neet-theory-empty';empty.textContent='その言葉では見つからなかったよ。別の言い方でも検索してみてね。';list.appendChild(empty)}}else empty?.remove();count.textContent=`${shown} / ${TOPICS.length}項目`}
input.addEventListener('input',render);sec.querySelectorAll('[data-neet-cat]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.neetCat;sec.querySelectorAll('[data-neet-cat]').forEach(x=>x.classList.toggle('active',x===b));render()}));render()}
function run(){installStyles();addTopGuide();enrichTopics();enrichHeadings();makeUnifiedLibrary()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();