(()=>{
'use strict';
const EXPLAIN={
  interval:{title:'音程',short:'2つの音の高さの距離。コードやスケールを作る一番小さい材料。',body:'音程は「何半音離れているか」と「何度の関係か」の両方で考えるよ。たとえば C→E は長3度、C→G は完全5度。コードの明るさ・暗さ・緊張感は、ほぼこの音程の組み合わせから生まれる。',example:'C–E–G = 長3度＋短3度 → Cメジャー。C–E♭–G = 短3度＋長3度 → Cマイナー。',use:'コード名を丸暗記するより、ルートから何度が入っているかを見ると応用が効く。'},
  key:{title:'音階・調号・五度圏',short:'キーは「曲の中で帰ってきたくなる中心」と、そこで使われやすい音の集合。',body:'メジャースケールは 全・全・半・全・全・全・半 の間隔。ナチュラルマイナーは 全・半・全・全・半・全・全。調号は、その音階を毎回♯/♭で書かなくて済むようにまとめて示したもの。五度圏では、時計回りに完全5度ずつ進むと♯が1つずつ増え、反時計回りでは♭が増える。',example:'Cメジャー = C D E F G A B。Aマイナーも同じ7音を使うので平行調。Gメジャーは F♯ が加わる。',use:'転調先や近いキーを探す時は五度圏を見ると早い。隣り合うキーほど共通音が多く、自然につながりやすい。'},
  triad:{title:'三和音と七の和音',short:'スケールの音を1音おきに積むと、そのキーの基本コードが作れる。',body:'三和音は基本的にルート・3度・5度。メジャー、マイナー、ディミニッシュなどは3度と5度の種類で決まる。さらに7度を重ねると7thコードになり、コードの機能や色彩がよりはっきりする。',example:'Cメジャー上では C, Dm, Em, F, G, Am, Bdim。7thにすると Cmaj7, Dm7, Em7, Fmaj7, G7, Am7, Bm7♭5。',use:'メロディ音がコードの3rdや7thに入ると、そのコードらしさが強く出やすい。'},
  function:{title:'機能和声',short:'コードを「安定・準備・緊張」の役割で見る考え方。',body:'長調では主にトニック(T)、サブドミナント(SD)、ドミナント(D)に分けて考える。トニックは落ち着き、サブドミナントは外へ広がる感じ、ドミナントはトニックへ戻りたがる緊張を作る。各コードは絶対に1つの役割だけを持つわけではないけど、進行を読む大きな手掛かりになる。',example:'Cメジャーなら C(I)=T、F(IV)=SD、G(V)=D。C→F→G→C は T→SD→D→T。',use:'「次に何のコードを置くか」で迷ったら、今が安定・展開・緊張のどこなのかを考えると選びやすい。'},
  cadence:{title:'終止（カデンツ）',short:'フレーズやセクションに「句読点」を作るコードの着地パターン。',body:'代表的なのは V→I の正格終止、IV→I の変格終止、V→vi の偽終止、I→V の半終止。V7→Iでは導音が主音へ、7thが下行して解決するため強い終止感が生まれる。',example:'G7→C は強い「終わった感」。G7→Am は着地を外す偽終止で、まだ続く感じを作れる。',use:'Aメロ終わり、サビ前、サビ終わりなど、曲の区切りごとに終止の強さを変えると展開が作りやすい。'},
  minor:{title:'短調の3種類',short:'短調はナチュラル・ハーモニック・メロディックの3つを使い分ける。',body:'ナチュラルマイナーは基本形。ハーモニックマイナーは第7音を半音上げて導音を作り、VやV7のドミナント機能を強くする。メロディックマイナーは上行時に第6・7音を上げる考え方から発展し、現代では独立したスケールとしても扱われる。',example:'A natural minor: A B C D E F G。A harmonic minor: G→G♯。A melodic minor: F→F♯, G→G♯。',use:'マイナー曲で E7→Am を強く響かせたいなら、G♯を含むハーモニックマイナーの発想が重要。'},
  tension:{title:'テンション',short:'7thコードの上に9th・11th・13thを加えて色を足す音。',body:'テンションは単に「スケール内なら全部OK」ではなく、コードトーンとの半音衝突やコードの機能も見る。特にドミナントでは♭9、♯9、♯11、♭13などのオルタードテンションが強い緊張を作る。',example:'Cmaj7に9th(D)を加えると Cmaj9。G7に♭9(A♭)を加えると G7(♭9)で、Cへ強く解決したくなる。',use:'メロディがテンションになっている時は、それを「外れ音」と処理せず、コードの色として残せるか考える。'},
  secondary:{title:'セカンダリードミナント',short:'一時的に別のコードを「仮のトニック」と見立て、そのV7を置く技法。',body:'ダイアトニック外の音を使って、目的のコードへの引力を強くする。表記は V/ii、V/V のように「何度に向かうドミナントか」で示す。転調とは限らず、数拍〜1小節だけ一時的に強調する場合も多い。',example:'Cキーで A7→Dm は V/ii→ii。D7→G は V/V→V。E7→Am は V/vi→vi。',use:'ダイアトニックだけだと平坦に感じる時、行き先のコードの5度上に7thコードを置くと推進力を作りやすい。'},
  modal:{title:'モーダルインターチェンジ（借用和音）',short:'同じ主音を持つ別の調・モードからコードを借りる。',body:'代表例はメジャーキーで同主短調から iv、♭VI、♭VII などを借りる方法。キー中心は保ちながら、一瞬だけ色や感情を変えられる。',example:'Cメジャーで Fm(iv)→C は、Cマイナー側からFmを借りた進行。A♭(♭VI)やB♭(♭VII)もよく使う。',use:'「切ない」「映画っぽい」「急に景色が変わる」感じが欲しい時にかなり強い。'},
  substitute:{title:'サブスティテュートドミナント',short:'ドミナント7thを、同じトライトーンを持つ♭II7系コードに置き換える。',body:'V7と、そのルートからトライトーン離れた7thコードは3rdと7thに共通のトライトーンを持つ。そのため同じ解決方向を保ちながら、ベースを半音進行にできる。',example:'Cへ進むG7の代わりに D♭7→C。D♭7のFとC♭は、G7のBとFに対応するトライトーン。',use:'II–V–Iを Dm7–D♭7–Cmaj7 のようにすると、ベースが D→D♭→C と滑らかに下がる。'},
  diminished:{title:'ディミニッシュ',short:'短3度を積み重ねた対称的な構造で、強い経過・接続機能を持つ。',body:'dim7は構成音がすべて短3度間隔なので、転回すると同じ構成音になる。1つのdim7を複数の導音和音として読み替えられるのが大きな特徴。',example:'Bdim7 = B D F A♭。転回しても同じ4音なので、Ddim7・Fdim7・A♭dim7と同じ音集合。',use:'目的コードの半音下にdim7を置く、ドミナントの♭9をルート省略した形として使う、ベースを半音でつなぐ、などに向く。'},
  modulation:{title:'転調',short:'曲の中心となるキーそのものを別のキーへ移す。',body:'共通コードを使うピボットコード転調、直接転調、ドミナントを使う転調などがある。一時的なセカンダリードミナントと違い、新しいキーがしばらく中心として感じられることがポイント。',example:'CメジャーのAmを、Gメジャーではiiとして読み替えて Am→D7→G と進めると、Gへ自然に転調できる。',use:'サビだけキーを上げたい、Bメロで景色を変えたい時は「共通コード→新キーのV→新I」を探すと設計しやすい。'},
  chordscale:{title:'コードスケール',short:'そのコード上で使える音を、コードの機能とテンションまで含めて整理する考え方。',body:'コードだけでなく「その瞬間のハーモニーに対して、メロディやアドリブでどの音が安定・緊張になるか」を見る。メジャーキーのダイアトニックコードには各度数に対応するモードを当てる考え方が基本。',example:'Cmaj7→C Ionian、Dm7→D Dorian、G7→G Mixolydian。ドミナントを強くしたい場合は altered など別候補も考える。',use:'コード進行に対してメロディを作る時、コードトーン→使えるテンション→注意音の順で見ると実践的。'},
  pedal:{title:'ペダルポイントとその他の和声技法',short:'ベースや共通音を保ちながら上のコードだけ動かすことで、まとまりと緊張を同時に作る。',body:'ペダルポイント、コンスタントストラクチャー、コンティギュアスモーションなどは、機能和声だけでは説明しにくい「音の形の連続性」を利用する技法。',example:'Cのベースを伸ばしたまま C–F/C–G/C–C と上だけ動かすと、トニックペダルの上で色が変化する。',use:'イントロ、間奏、映画的な場面、浮遊感のある進行などに使いやすい。'}
};
function card(key){const x=EXPLAIN[key];return `<article class="neet-explain"><div class="neet-explain-head"><span>📖</span><div><b>${x.title}</b><small>${x.short}</small></div></div><div class="neet-explain-body"><p>${x.body}</p><div><strong>例</strong>${x.example}</div><div><strong>作曲でどう使う？</strong>${x.use}</div></div></article>`}
function installStyles(){if(document.getElementById('neet-theory-guide-style'))return;const s=document.createElement('style');s.id='neet-theory-guide-style';s.textContent=`.neet-explain{margin:10px 0 0;padding:12px;border:1px solid var(--line,#ded6c9);border-radius:14px;background:#fff}.neet-explain-head{display:flex;gap:9px;align-items:flex-start}.neet-explain-head>span{display:grid;place-items:center;width:32px;height:32px;flex:0 0 32px;border-radius:10px;background:var(--soft,#f4eee4)}.neet-explain-head b{display:block;font-size:.9rem}.neet-explain-head small{display:block;margin-top:2px;color:var(--muted,#71695f);font-size:.73rem;line-height:1.45}.neet-explain-body{margin-top:9px;font-size:.78rem;line-height:1.68;color:var(--ink,#1f2937)}.neet-explain-body p{margin:0 0 8px}.neet-explain-body>div{margin-top:7px;padding:8px 9px;border-radius:10px;background:var(--soft,#f4eee4)}.neet-explain-body strong{display:block;margin-bottom:3px;color:var(--accent,#8b6f47);font-size:.68rem;letter-spacing:.06em}.neet-explain summary{cursor:pointer}.neet-guide-top{margin:0 0 13px;padding:12px 13px;border:1px solid #d8c9b5;border-radius:14px;background:#fff9ef}.neet-guide-top b{display:block;margin-bottom:4px}.neet-guide-top p{margin:0;color:#685a48;font-size:.78rem;line-height:1.6}.neet-guide-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:9px}.neet-guide-grid a{padding:8px 9px;border:1px solid #e3d8c9;border-radius:10px;background:#fff;color:inherit;text-decoration:none;font-size:.75rem;font-weight:850}@media(max-width:650px){.neet-guide-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function addTopGuide(){const lead=document.querySelector('.source-note')||document.querySelector('.lead');if(!lead||document.querySelector('.neet-guide-top'))return;const box=document.createElement('section');box.className='neet-guide-top';box.innerHTML=`<b>このページの見方</b><p>「名前を覚える」より、①何の音でできている？ → ②そのコードは今どんな役割？ → ③どこへ進みたがってる？ の順で見ると理論が作曲につながるよ。説明は「意味 → 例 → 作曲での使い方」の順に読めるよう強化してある。</p><div class="neet-guide-grid"><a href="#">🎼 基礎：音階とコード</a><a href="#">🧭 機能：T / SD / D</a><a href="#">✨ 色彩：テンション・借用</a><a href="#">🚪 発展：転調・代理</a></div>`;lead.insertAdjacentElement('afterend',box)}
function enrichTopics(){const topics=[...document.querySelectorAll('.topic')];const map=[['音程','interval'],['音階','key'],['調号','key'],['三和音','triad'],['七の和音','triad'],['機能','function'],['終止','cadence'],['短調','minor'],['テンション','tension'],['セカンダリー','secondary'],['セカンダリードミナント','secondary'],['モーダル','modal'],['借用','modal'],['サブスティテュート','substitute'],['subV','substitute'],['ディミニッシュ','diminished'],['転調','modulation'],['コードスケール','chordscale'],['ペダル','pedal']];topics.forEach(t=>{const text=t.textContent||'';const hit=map.find(([n])=>text.includes(n));if(hit&&!t.querySelector('.neet-explain'))t.insertAdjacentHTML('beforeend',card(hit[1]))})
}
function enrichHeadings(){const all=[...document.querySelectorAll('h2,h3')];const pairs=[['使えるスケール','chordscale'],['メロディ音の役割','function'],['色を変えるコード','modal'],['キー','key'],['ダイアトニック','triad'],['進行','function']];pairs.forEach(([word,key])=>{const h=all.find(x=>(x.textContent||'').includes(word));const host=h?.parentElement;if(host&&!host.querySelector('.neet-explain'))host.insertAdjacentHTML('beforeend',card(key))})}
function makeGlossary(){if(document.getElementById('neetQuickGlossary'))return;const root=document.querySelector('.wrap')||document.body;const sec=document.createElement('section');sec.className='card wide';sec.id='neetQuickGlossary';sec.style.marginTop='13px';sec.innerHTML=`<h2>📚 ことばから理解する理論ミニ辞典 <span class="hint">迷った時にここを見る</span></h2><div class="library">${['interval','key','triad','function','cadence','minor','tension','secondary','modal','substitute','diminished','modulation','chordscale','pedal'].map(k=>card(k)).join('')}</div>`;root.appendChild(sec)}
function run(){installStyles();addTopGuide();enrichTopics();enrichHeadings();makeGlossary()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();