(()=>{'use strict';
const DB_NAME='neet-note-media-v1',STORE='voice-memos';let db,recorder,chunks=[],timer,seconds=0,currentId='';
const list=document.getElementById('voiceList'),search=document.getElementById('voiceSearch'),recordBtn=document.getElementById('recordBtn'),state=document.getElementById('recordState'),time=document.getElementById('recordTime'),editor=document.getElementById('voiceEditor'),title=document.getElementById('voiceTitle'),audio=document.getElementById('voiceAudio'),status=document.getElementById('voiceStatus');
const openDb=()=>new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)});
const tx=(mode='readonly')=>db.transaction(STORE,mode).objectStore(STORE);const getAll=()=>new Promise((r,j)=>{const q=tx().getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error)});const put=x=>new Promise((r,j)=>{const q=tx('readwrite').put(x);q.onsuccess=()=>r();q.onerror=()=>j(q.error)});const remove=id=>new Promise((r,j)=>{const q=tx('readwrite').delete(id);q.onsuccess=()=>r();q.onerror=()=>j(q.error)});
function format(sec){return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function render(){const q=search.value.trim().toLowerCase(),items=(await getAll()).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).filter(x=>(x.title||'').toLowerCase().includes(q));list.innerHTML=items.length?'':'<div style="padding:16px;text-align:center;color:var(--muted)">まだ録音がないよ。</div>';items.forEach(x=>{const b=document.createElement('button');b.className='voice-item'+(x.id===currentId?' active':'');b.innerHTML=`<b>${esc(x.title||'無題の録音')}</b><small>${format(Math.round(x.duration||0))}</small>`;b.onclick=()=>select(x.id);list.appendChild(b)})}
async function select(id){const items=await getAll(),x=items.find(v=>v.id===id);if(!x)return;currentId=id;title.value=x.title||'';audio.src=URL.createObjectURL(x.blob);editor.hidden=false;status.textContent='保存済み';render()}
async function start(){if(!navigator.mediaDevices?.getUserMedia){alert('このブラウザでは録音できないよ。');return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];seconds=0;time.textContent='00:00';recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),now=new Date().toISOString(),id=crypto.randomUUID?crypto.randomUUID():String(Date.now());await put({id,title:`録音 ${new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date())}`,blob,duration:seconds,createdAt:now,updatedAt:now});currentId=id;await select(id)};recorder.start();recordBtn.classList.add('recording');state.textContent='録音中… もう一度タップで停止';timer=setInterval(()=>{seconds++;time.textContent=format(seconds)},1000)}
function stop(){recorder?.stop();clearInterval(timer);recordBtn.classList.remove('recording');state.textContent='タップして録音'}
recordBtn.onclick=()=>recorder?.state==='recording'?stop():start().catch(()=>alert('マイクの使用を許可してね。'));search.oninput=render;title.oninput=async()=>{if(!currentId)return;const items=await getAll(),x=items.find(v=>v.id===currentId);if(!x)return;x.title=title.value.trim();x.updatedAt=new Date().toISOString();await put(x);status.textContent='保存済み';render()};document.getElementById('deleteVoice').onclick=async()=>{if(!currentId||!confirm('この録音を削除しますか？'))return;await remove(currentId);currentId='';editor.hidden=true;audio.removeAttribute('src');render()};document.getElementById('downloadVoice').onclick=async()=>{if(!audio.src)return;const a=document.createElement('a');a.href=audio.src;a.download=(title.value.trim()||'ボイスメモ')+'.webm';a.click()};openDb().then(render).catch(()=>alert('ボイスメモの保存領域を開けなかったよ。'));
})();